#!/bin/bash

################################################################################

for (( ; ; )); do # loop dashbord

  source /etc/pi-node/include/color
  source /etc/pi-node/config

  # output specific data
  WALLET_TXLAST="$(grep "Progress" /tmp/dash.data.tmp | awk '{ print $3 }')"
  REPO_VERSION="$(grep "Repo_version" /tmp/dash.data.tmp | awk '{ print $3 }')"
  SYSTEM_CLOCK="$(grep "system_clock" /tmp/dash.data.tmp | awk '{ print $3 }')"

  source . # something!

  clear
  # dashbord
  printf '%b' "
${GR:?}                       ${GR:?} Pi-Node ${REPO_VERSION:?}        ${SYSTEM_CLOCK:?}
${CB:?}        ##   ##        ${N0:?} Fullnode + Stakebox       ${MASTER_STATUS:?} ${PROOF_STATUS:?} ${THEME_STATUS:?} ${POS_STATUS:?} ${TOR_STATUS:?} ${LAN_STATUS:?}
${CB:?}        ##.  ##        ${GR:?} -----------------------------------------${N0:?}
${CB:?}    ##############     ${N0:?} Load ${SYSTEM_LOAD:?} temp ${CPU_CTEMP:?} ${CPU_FTEMP:?}
${CB:?}      ###      ####    ${N0:?} Free Mem ${FREE_MEM:?}/${TOTAL_MEM:?} HDDuse ${USED_HDD:?} (${USED_HDD_P:?})
${CB:?}      ###.    ,###     ${N0:?} ${SYSTEM_USER:?}@${IP_ADDRESS:?} ${G0:?}⇩${N0:?} ${DOWNLOAD:?} ${R1:?}⇧${N0:?} ${UPLOAD:?}
${CB:?}      ###########      ${N0:?} ${WALLET_DAEMON:?} ${WALLET_VERSION:?} ${WALLET_CHAIN:?} Sync ${WALLET_SYNC:?}
${CB:?}      ###       ###    ${N0:?} WAN ${PUBLIC_IP:?} Peers ${WALLET_PEERS_TOTAL:?} ${WALLET_PEERS_LATEST:?} ${WALLET_PEERS_OTHER:?}
${CB:?}      ###.     ,###    ${N0:?}
${CB:?}    ##############     ${N0:?} Balance ${WALLET_BALANCES:?} ${WALLET_POS_REWARDS:?} ${WALLET_INPUTS_NODES:?}
${CB:?}        ##   ##        ${N0:?} TxCount ${WALLET_TXCOUNT:?} Mempool ${WALLET_MEMPOOL:?} Block ${WALLET_HEADS:?}
${CB:?}        ##   ##        ${N0:?} ${TIMELINE:?}

${TX:?} ${WALLET_TXLAST:?}

${LAST_LOG:?}
"

  sleep "${TIME:?}"
done

# END
