#!/bin/bash

# By Rainman
# V20220104
# 0.0.4.2

source /usr/local/bin/include/pinode/pinode.conf 2>&1

for (( ; ; )); do # loop dashbord

  # save dashbord time
  echo "$(LC_ALL=de_US.utf8 date +%s 2>&1)" >"${LOG_DIR:?}"/node_data/wallet/data/time.dashbord 2>/dev/null

  source /usr/local/bin/include/pinode/color 2>&1
  source /usr/local/bin/include/pinode/functions 2>&1
  source /usr/local/bin/include/pinode/time_fix 2>&1

  clear
  # dashbord
  printf '%b' "
${RC:?}                       ${RC:?} Pi-Node ${REPO_VERSION:?} pinode          ${SYSTEM_CLOCK:?}
${CB:?}        ##   ##        ${N0:?} Fullnode + Stakebox       ${MASTER_STATUS:?} ${PROOF_STATUS:?} ${THEME_STATUS:?} ${POS_STATUS:?} ${TOR_STATUS:?} ${LAN_STATUS:?}
${CB:?}        ##.  ##        ${RC:?} -----------------------------------------${N0:?}
${CB:?}    ##############     ${N0:?} Load ${SYSTEM_LOAD:?} temp ${CPU_CTEMP:?}°C ${CPU_FTEMP:?}°F
${CB:?}      ###      ####    ${N0:?} Free Mem ${FREE_MEM:?}/${TOTAL_MEM:?} HDDuse ${USED_HDD:?} (${USED_HDD_P:?})
${CB:?}      ###.    ,###     ${N0:?} ${SYSTEM_USER:?}@${IP_ADDRESS:?} ${G0:?}⇩${N0:?} ${DOWNLOAD:?} ${R1:?}⇧${N0:?} ${UPLOAD:?}
${CB:?}      ###########      ${N0:?} ${WALLET_DAEMON:?} ${WALLET_VERSION:?} ${WALLET_CHAIN:?} Sync ${WALLET_SYNC:?}
${CB:?}      ###       ###    ${N0:?} WAN ${PUBLIC_IP:?} Peers ${WALLET_PEERS_TOTAL:?} ${WALLET_PEERS_LATEST:?} ${WALLET_PEERS_OTHER:?}
${CB:?}      ###.     ,###    ${N0:?}
${CB:?}    ##############     ${N0:?} Balance ${WALLET_BALANCES:?} ${WALLET_POS_REWARDS:?} ${WALLET_INPUTS_NODES:?}
${CB:?}        ##   ##        ${N0:?} TxCount ${WALLET_TXCOUNT:?} Mempool ${WALLET_MEMPOOL:?} Block ${WALLET_HEADS:?}
${CB:?}        ##   ##        ${N0:?} ${TIMELINE:?}

${TX:?} ${WALLET_TXLAST:?}

${LAST_LOG:?}
"

  sleep "${TIME:?}"
done

# END
