#!/bin/bash

# By Rainman
# V20210912
# 0.0.4.0

# setfont for display HyperPixel 4.0, 800×480 (~235 PPI)
sudo setfont /usr/share/consolefonts/Lat7-Terminus24x12.psf.gz

for (( ; ; )); do # loop dashbord

  source /usr/local/bin/color
  source /usr/local/bin/functions
  source /usr/local/bin/time_fix

  clear
  # dashbord
  printf '%b' "

                      ${Y1:?}Pi${Y0:?}Trump ${Y1:?}v0.1.6.2 ${GR:?}pitrump${N0:?}         ${CLOCK:?}
                      TrumpCoin Fullnode                   ${INTERFACE:?}
$RC  #################  ${GR:?} -----------------------------------------${N0:?}
$RC  #################  ${N0:?} Load ${LOAD:?} temp ${CPU_CTEMP:?}°C ${CPU_FTEMP:?}°F
$RC  ##    #####    ##  ${N0:?} Free Mem ${G0:?}${FREE_MEM:?}M${N0:?}/${G0:?}${TOTAL_MEM:?}M${N0:?} HDDuse ${G0?:}${USED_HDD:?} (${USED_HDD_P:?})${N0:?}
$RC        #####
$RC        #####        ${N0:?} ${USER:?}@${CY:?}${IP_ADDRESS:?} ${G0:?}⇩${N0:?} ${DOWNLOAD:?} ${R1:?}⇧${N0:?} ${UPLOAD:?}
$RC        #####        ${N0:?} trumpcoin ${G0:?}${WALLET_VERSION:?} ${WALLET_CHAIN:?}${N0:?} Sync ${G0:?}${WALLET_SYNC:?}%${N0:?}
$RC        #####        ${N0:?} WAN ${CY:?}${PUBLIC_IP:?} ${N0:?}Peers ${P1:?}${WALLET_PEERS:?}${N0:?} ${GR:?}0 0${N0:?}
$RC       #######       ${N0:?} Balance ${G0:?}${WALLET_BALANCE:?}${N0:?} Stakes ${G0:?}0${N0:?} Inputs ${G0:?}0${N0:?}
$RC     ###########     ${N0:?} TxCount ${G0:?}${WALLET_TXCOUNT:?}${N0:?} Mempool ${WALLET_MEMPOOL:?}${N0:?} Block ${WALLET_HEADS:?}${N0:?}

${RC_LOADING:?}${N0:?}


${LAST_LOG:?}
"

  sleep "${TIME:?}"

done
