#!/bin/bash

# By Rainman
# V20210712
# 0.0.3.7

# setfont for display HyperPixel 4.0, 800×480 (~235 PPI)
sudo setfont /usr/share/consolefonts/Lat7-Terminus24x12.psf.gz

for (( ; ; )); do # loop dashbord

  source /usr/local/bin/color
  source /usr/local/bin/functions
  source /usr/local/bin/time_fix

  clear
  # dashbord
  printf '%b' "

                      ${Y1:?}PiTrump v0.1 ${GR:?}pitrump${N0:?}             ${CLOCK:?}
                      TrumpCoin Fullnode                   ${INTERFACE:?}
$Y1   ################# ${GR:?} -----------------------------------------${N0:?}
$Y1   ################# ${N0:?} Load ${LOAD:?} temp ${CPU_CTEMP:?}°C ${CPU_FTEMP:?}°F
$Y1   ##    #####    ## ${N0:?} Free Mem ${G0:?}${FREE_MEM:?}M${N0:?} / ${G0:?}${TOTAL_MEM:?}M${N0:?} HDDuse ${G0?:}${USED_HDD:?} (${USED_HDD_P:?})${N0:?}
$Y1         #####
$Y1         #####       ${N0:?} $USER${CY:?}${IP_ADDRESS:?} ${G0:?}⇩${N0:?} ${DOWNLOAD:?} ${R1:?}⇧${N0:?} ${UPLOAD:?}
$Y1         #####
$Y1         #####
$Y1        #######
$Y1      ###########$N0


"

  sleep "${TIME:?}"

done
