#!/bin/bash

# By Rainman
# V20211512
# 0.0.3.2

# create addnodes file
function addnodes() {
  # update addnodes, failed peers, along with ticker price (every half, & hour)
  if [[ "$(date '+%T' 2>&1 | egrep "[0-9]+:30:[0-9]+|[0-9]+:00:[0-9]+" 2>&1)" ]]; then
    rm "$LOG_DIR"/node_data/nodes &>/dev/null
    printf '%b' "${LOG_DATE:?} Status() Update.Nodes() Looking for new peers!${N0:?}\n" >>"${WALLET_LOG_DIR:?}"/debug.log 2>&1
  fi
  # create failed connection list, remove duplicates, sort
  egrep -o " to [a0-z9]+.[a0-z9]+.[a0-z9]+.[a0-z9]+:[0-9]+ failed" "${WALLET_LOG_DIR:?}"/debug.log 2>&1 |
    awk '!a[$0]++' 2>&1 | sort -n 2>&1 | awk '{ print $2 }' >"$LOG_DIR"/node_data/failed 2>&1
}

# cleanup node files
function addnodes_cleanup() {
  # output connected peers, disregard with failed connections
  egrep "192.168.1.*:15110" "$LOG_DIR"/node_data/failed 2>&1 |
    egrep -o "192.168.1.[0-9]+" >>"$LOG_DIR"/node_data/failed 2>&1
  # node_data/addnodes
  cat "$LOG_DIR"/node_data/addnodes 2>&1 | awk '!a[$0]++' 2>&1 |
    # remove with failed peers file
    grep -v -f "$LOG_DIR"/node_data/failed >"$LOG_DIR"/node_data/addnodes 2>&1
  # $(whoami)/addnodes
  cat /home/"$(whoami)"/addnodes 2>&1 | awk '!a[$0]++' 2>&1 |
    # remove with failed peers file
    grep -v -f "$LOG_DIR"/node_data/success >"$LOG_DIR"/node_data/addnodes 2>&1
}
