#!/bin/bash

################################################################################

source /etc/pi-node/include/color

################################################################################

# variables
REPO_URL="https://github.com/FreedomCoin-Project/FreedomCoin-Core.git"
DIR_NAME="FreedomCoin-Core"

################################################################################

# update and install dependencies
sudo apt update
sudo apt upgrade -y
sudo apt install -y \
  build-essential libtool autotools-dev automake pkg-config bsdmainutils curl \
  git python3 libssl-dev libevent-dev libboost-system-dev libboost-filesystem-dev \
  libboost-test-dev libboost-thread-dev libminiupnpc-dev libzmq3-dev libprotobuf-dev \
  protobuf-compiler libqrencode-dev libdb-dev libdb++-dev libsqlite3-dev
sudo apt-get autoremove -y

################################################################################

# clone repository
git clone --recursive "$REPO_URL"
cd "$DIR_NAME"

################################################################################

# start counting (seconds)
START="$SECONDS"

# build steps
./autogen.sh

# if aarch64
if [[ "$(uname -m)" == "aarch64" ]] &>/dev/null; then
  # patch missing <deque> include
  sed -i '/#include <event2\/keyvalq_struct.h>/a #include <deque>' "$HOME/FreedomCoin-Core/src/httpserver.cpp"
  # patch non-constexpr sysconf() usage in Catch2 test framework
  sed -i 's|static constexpr std::size_t sigStackSize = .*;|static const std::size_t sigStackSize = 32768;|' "$HOME/FreedomCoin-Core/src/contrib/catch/catch.hpp"
  # add missing include <memory> to chiabls/src/threshold.cpp
  sed -i '1s/^/#include <memory>\n/' "$HOME/FreedomCoin-Core/src/chiabls/src/threshold.cpp"
fi

################################################################################

# install rust and cargo
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
source $HOME/.cargo/env

################################################################################

./configure --enable-cxx --disable-tests --disable-bench --with-incompatible-bdb
make -j$(nproc)

################################################################################

# optional: Strip binaries to save space
strip src/freedomcoind src/freedomcoin-cli || true

################################################################################

# calculate build time
DURATION=$(echo "$SECONDS-$START" | bc 2>/dev/null)
TIMER=$(printf '%dh:%dm:%ds\n' $(("$DURATION/3600")) $(("$DURATION%3600/60")) $(("$DURATION%60")))

echo
printf '%b' "[${N0}!!${N0}] Console : Build time: ${G1}$TIMER${N0}\n"
echo
read -r -p "[Ok] Press Enter to continue" </dev/tty
echo

# END
