#!/bin/bash

set -e

# variables
REPO_URL="https://github.com/FreedomCoin-Project/FreedomCoin-Core.git"
DIR_NAME="FreedomCoin-Core"

# update and install dependencies
sudo apt update
sudo apt upgrade -y
sudo apt install -y \
  build-essential libtool autotools-dev automake pkg-config bsdmainutils curl \
  git python3 libssl-dev libevent-dev libboost-system-dev libboost-filesystem-dev \
  libboost-test-dev libboost-thread-dev libminiupnpc-dev libzmq3-dev libprotobuf-dev \
  protobuf-compiler libqrencode-dev libdb-dev libdb++-dev libsqlite3-dev

# clone repository
git clone --recursive "$REPO_URL"
cd "$DIR_NAME"

# build steps
./autogen.sh
./configure --enable-cxx --disable-tests --disable-bench --with-incompatible-bdb
make -j$(nproc)

# optional: Strip binaries to save space
strip src/freedomcoind src/freedomcoin-cli || true

# done
echo "[!!] FreedomCoin build complete!"

# END
