#!/bin/bash

################################################################################

source /etc/pi-node/include/color

################################################################################

# if no daemon found, if no client found
if [[ ! -f /usr/local/bin/freedomcoind && ! -f /usr/local/bin/freedomcoin-cli ]] &>/dev/null; then
  printf '%b' "[${Y1}Ok${N0}] Console : Daemon/Client not found!\n"

  # linux
  LATEST_RELEASE="$(curl -s https://api.github.com/repos/FreedomCoin-Project/FreedomCoin-Core/releases/latest | grep '"tag_name"' | cut -d '"' -f 4)"
  printf '%b' "[${G1}OK${N0}] curl    : Checking latest release!\n"

  # machine
  UNAME_M="$(uname -m)"

  if [[ "$(echo "$UNAME_M" | grep -c "x86_64")" == "1" ]] &>/dev/null; then
    # x86_64
    WALLET_DOWNLOAD="FreedomCoin-Core-Linux"
  fi
  if [[ "$(echo "$UNAME_M" | grep -c "aarch64")" == "1" ]] &>/dev/null; then
    # aarch64
    WALLET_DOWNLOAD="FreedomCoin-aarch64"
  fi
  if [[ "$(echo "$UNAME_M" | grep -c "arm")" == "1" ]] &>/dev/null; then
    # arm
    WALLET_DOWNLOAD="FreedomCoin_arm"
  fi

  # if missing
  if [[ ! -f "$HOME"/"$WALLET_DOWNLOAD".zip ]] &>/dev/null; then
    # change directory, download WALLET_DOWNLOAD.zip
    cd || exit && wget -c https://github.com/FreedomCoin-Project/FreedomCoin-Core/releases/download/"$LATEST_RELEASE"/"$WALLET_DOWNLOAD".zip
    printf '%b' "[${G1}OK${N0}] wget    : Download complete!\n"
  fi

  # if missing
  if [[ ! -d "$HOME"/"$WALLET_DOWNLOAD" ]] &>/dev/null; then
    # unzip file
    unzip "$WALLET_DOWNLOAD".zip
    printf '%b' "[${G1}OK${N0}] unzip   : Unzip complete!\n"
  fi

  # clean up __MACOSX & zip
  rm -r "$HOME"/__MACOSX &>/dev/null
  rm "$WALLET_DOWNLOAD".zip &>/dev/null

  # install deamon
  sudo mv "$HOME"/"$WALLET_DOWNLOAD"/freedomcoind /usr/local/bin
  printf '%b' "[${G1}OK${N0}] mv      : freedomcoind installed!\n"

  # install client
  sudo mv "$HOME"/"$WALLET_DOWNLOAD"/freedomcoin-cli /usr/local/bin
  printf '%b' "[${G1}OK${N0}] mv      : freedomcoin-cli installed!\n"

  # remove old directory
  rm -r "$HOME"/"$WALLET_DOWNLOAD"

  # fix ownership
  sudo chown "$(whoami)":"$(whoami)" /usr/local/bin/freedomcoin* 2>/dev/null
  printf '%b' "[${G1}OK${N0}] chown   : Fixing ownership!\n"
else
  printf '%b' "[${G1}OK${N0}] Console : FreedomCoin Daemon and Client installed!\n"
fi

# END
