#!/bin/bash

################################################################################

source /etc/pi-node/include/color

################################################################################
# find daemon
################################################################################

# if no configuration
if [[ "$(grep -c "WALLET_DAEMON=" /etc/pi-node/config)" -eq "0" ]] &>/dev/null; then
  printf '%b' "[${Y1}Ok${N0}] Daemon  : Searching for wallet daemon..\n"
  # find freedomcoi daemon
  DAE_FOUND="$(find /usr/local/bin -name "freedomcoind" 2>/dev/null | head -1)"
  # if zero
  if [[ -z "$DAE_FOUND" ]] &>/dev/null; then
    DAE_FOUND="$(find "$HOME" -name "freedomcoind" 2>/dev/null | head -1)"
  fi
  # if found
  if [[ -f "$DAE_FOUND" ]] &>/dev/null; then
    printf '%b' "[${G1}OK${N0}] Config  : Found ${CY}$DAE_FOUND${N0}\n"
    # update configuration
    echo "WALLET_DAEMON=$DAE_FOUND" >>/etc/pi-node/config
  fi
else
  # configuration daemon found
  DAE_FOUND="$(grep "WALLET_DAEMON=" /etc/pi-node/config | awk -F= '{ print $2 }')"
  # pidof daemon
  DAE_PID="$(pidof "$(echo "$DAE_FOUND" | awk -F/ '{ print $NF }')")"
  # active daemon
  if [[ -n "$DAE_PID" ]] &>/dev/null; then
    DAE_ACTIVE="${G1}Online${N0} PID: $DAE_PID"
  else
    DAE_ACTIVE="${GR}Offline${N0}"
  fi
  # if configuration found
  printf '%b' "[${G1}OK${N0}] Daemon  : Found ${CY}$DAE_FOUND${N0} in configuration!\n"
  printf '%b' "[${G1}OK${N0}] Status  : Daemon $DAE_ACTIVE\n"
fi

################################################################################
# find client
################################################################################

# if no configuration
if [[ "$(grep -c "WALLET_CLIENT=" /etc/pi-node/config)" -eq "0" ]] &>/dev/null; then
  printf '%b' "[${Y1}Ok${N0}] Client  : Searching for wallet client..\n"
  CLI_FOUND="$(find /usr/local/bin -name "freedomcoin-cli" 2>/dev/null | head -1)"
  # if zero
  if [[ -z "$CLI_FOUND" ]] &>/dev/null; then
    CLI_FOUND="$(find "$HOME" -name "freedomcoin-cli" 2>/dev/null | head -1)"
  fi
  # if found
  if [[ -f "$CLI_FOUND" ]] &>/dev/null; then
    printf '%b' "[${G1}OK${N0}] Config  : Found ${CY}$CLI_FOUND${N0}\n"
    # update configuration
    echo "WALLET_CLIENT=$CLI_FOUND" >>/etc/pi-node/config
  fi
else
  # configuration client found
  CLI_FOUND="$(grep "WALLET_CLIENT=" /etc/pi-node/config | awk -F= '{ print $2 }')"
  # pidof client
  CLI_PID="$(pidof "$(echo "$CLI_FOUND" | awk -F/ '{ print $NF }')")"
  # active client
  if [[ -n "$CLI_PID" ]] &>/dev/null; then
    CLI_ACTIVE="${G1}Online${N0} PID: $CLI_PID"
  else
    CLI_ACTIVE="${GR}Offline${N0}"
  fi
  # if configuration found
  printf '%b' "[${G1}OK${N0}] Client  : Found ${CY}$CLI_FOUND${N0} in configuration!\n"
  printf '%b' "[${G1}OK${N0}] Status  : Client $CLI_ACTIVE\n"
fi

################################################################################
# find wallet.conf
################################################################################

# if no configuration
if [[ "$(grep -c "WALLET_CONF=" /etc/pi-node/config)" -eq "0" ]] &>/dev/null; then
  printf '%b' "[${Y1}Ok${N0}] Wallet  : Searching for trumpcoin.conf..\n"
  CON_FOUND="$(find "$HOME" -name "trumpcoin.conf" 2>/dev/null | head -1)"
  # if zero
  if [[ -z "$CON_FOUND" ]] &>/dev/null; then
    CON_FOUND="$(find /usr/local/bin -name "trumpcoin.conf" 2>/dev/null | head -1)"
  fi
  # if found
  if [[ -f "$CON_FOUND" ]] &>/dev/null; then
    printf '%b' "[${G1}OK${N0}] Config  : Found ${CY}$CON_FOUND${N0}\n"
    # update configuration
    echo "WALLET_CONF=$CON_FOUND" >>/etc/pi-node/config
  fi
else
  # configuration wallet.conf found
  CON_FOUND="$(grep "WALLET_CONF=" /etc/pi-node/config | awk -F= '{ print $2 }')"
  # if configuration found
  printf '%b' "[${G1}OK${N0}] Config  : Found ${CY}$CON_FOUND${N0} in configuration!\n"
fi

################################################################################
# find patriotnode.conf
################################################################################

# if no configuration
if [[ "$(grep -c "WALLET_MASTER=" /etc/pi-node/config)" -eq "0" ]] &>/dev/null; then
  printf '%b' "[${Y1}Ok${N0}] Master  : Searching for patriotnode.conf..\n"
  MAS_FOUND="$(find "$HOME" -name "patriotnode.conf" 2>/dev/null | head -1)"
  # if zero
  if [[ -z "$MAS_FOUND" ]] &>/dev/null; then
    MAS_FOUND="$(find /usr/local/bin -name "patriotnode.conf" 2>/dev/null | head -1)"
  fi
  # if found
  if [[ -f "$MAS_FOUND" ]] &>/dev/null; then
    printf '%b' "[${G1}OK${N0}] Config  : Found ${CY}$MAS_FOUND${N0}\n"
    # update configuration
    echo "WALLET_MASTER=$MAS_FOUND" >>/etc/pi-node/config
  fi
else
  # configuration patriotnode.conf found
  MAS_FOUND="$(grep "WALLET_MASTER=" /etc/pi-node/config | awk -F= '{ print $2 }')"
  # if configuration found
  printf '%b' "[${G1}OK${N0}] Master  : Found ${CY}$MAS_FOUND${N0} in configuration!\n"
fi

# END
