#!/bin/bash

################################################################################

# colors
B0='\e[34m'   # Blue
B1='\e[94m'   # Blue light
CY='\e[36m'   # Cyan
C1='\e[96m'   # Cyan light
G0='\e[32m'   # Green
G1='\e[92m'   # Green light
GR='\e[90m'   # Grey
N0='\033[0m'  # No color
P0='\e[0;35m' # Purple
P1='\e[1;35m' # Purple light
R0='\e[31m'   # Red
R1='\e[91m'   # Red light
Y0='\e[33m'   # Yellow
Y1='\e[93m'   # Yellow light

################################################################################
# find daemon
################################################################################

# if no configuration
if [[ "$(grep -c "WALLET_DAEMON=" /etc/pi-node/config)" -eq "0" ]] &>/dev/null; then
  printf '%b' "[${Y1}Ok${N0}] Daemon  : Searching for wallet daemon..\n"
  # find freedomcoi daemon
  DAE_FOUND="$(find / -name "freedomcoind" 2>/dev/null | head -1)"
  # if found
  if [[ -f "$DAE_FOUND" ]] &>/dev/null; then
    printf '%b' "[${G1}OK${N0}] Daemon  : Found ${CY}$DAE_FOUND${N0}! Updating configuration!\n"
    # update configuration
    echo "WALLET_DAEMON=$DAE_FOUND" >>/etc/pi-node/config
  fi
else
  # configuration daemon found
  DAE_FOUND="$(grep "WALLET_DAEMON=" /etc/pi-node/config | awk -F= '{ print $2 }')"
  # pidof daemon
  DAE_PID="$(pidof "$(echo "$DAE_FOUND" | awk -F/ '{ print $NF }')")"
  # active daemon
  if [[ -n "$DAE_PID" ]] &>/dev/null; then
    DAE_ACTIVE="${G1}Online${N0} PID: $DAE_PID"
  else
    DAE_ACTIVE="${GR}Offline${N0}"
  fi
  # if configuration found
  printf '%b' "[${G1}OK${N0}] Daemon  : Found ${CY}$DAE_FOUND${N0} in configuration!\n"
  printf '%b' "[${G1}OK${N0}] Status  : Daemon $DAE_ACTIVE\n"
fi

################################################################################
# find client
################################################################################

# if no configuration
if [[ "$(grep -c "WALLET_CLIENT=" /etc/pi-node/config)" -eq "0" ]] &>/dev/null; then
  printf '%b' "[${Y1}Ok${N0}] Client  : Searching for wallet client..\n"
  CLI_FOUND="$(find / -name "freedomcoin-cli" 2>/dev/null | head -1)"
  # if found
  if [[ -f "$CLI_FOUND" ]] &>/dev/null; then
    printf '%b' "[${G1}OK${N0}] Client  : Found ${CY}$CLI_FOUND${N0}! Updating configuration!\n"
    # update configuration
    echo "WALLET_CLIENT=$CLI_FOUND" >>/etc/pi-node/config
  fi
else
  # configuration client found
  CLI_FOUND="$(grep "WALLET_CLIENT=" /etc/pi-node/config | awk -F= '{ print $2 }')"
  # pidof client
  CLI_PID="$(pidof "$(echo "$CLI_FOUND" | awk -F/ '{ print $NF }')")"
  # active client
  if [[ -n "$CLI_PID" ]] &>/dev/null; then
    CLI_ACTIVE="${G1}Online${N0} PID: $CLI_PID"
  else
    CLI_ACTIVE="${GR}Offline${N0}"
  fi
  # if configuration found
  printf '%b' "[${G1}OK${N0}] Client  : Found ${CY}$CLI_FOUND${N0} in configuration!\n"
  printf '%b' "[${G1}OK${N0}] Status  : Client $CLI_ACTIVE\n"
fi

################################################################################
# find wallet
################################################################################

# if no configuration
if [[ "$(grep -c "WALLET_DAT=" /etc/pi-node/config)" -eq "0" ]] &>/dev/null; then
  printf '%b' "[${Y1}Ok${N0}] PrivKey : Searching for private key..\n"
  DAT_FOUND="$(find / -name "wallet.dat" 2>/dev/null | head -1)"
  # if found
  if [[ -f "$DAT_FOUND" ]] &>/dev/null; then
    printf '%b' "[${G1}OK${N0}] PrivKey : Found ${CY}$DAT_FOUND${N0}! Updating configuration!\n"
    # update configuration
    echo "WALLET_DAT=$DAT_FOUND" >>/etc/pi-node/config
  fi
else
  # configuration client found
  DAT_FOUND="$(grep "WALLET_DAT=" /etc/pi-node/config | awk -F= '{ print $2 }')"
  # if configuration found
  printf '%b' "[${G1}OK${N0}] PrivKey : Found ${CY}$DAT_FOUND${N0} in configuration!\n"
fi

# END
