#!/bin/bash

# By Rainman
# V20210712
# 0.0.4.0

# shellcheck disable=SC2034  # Unused variables left for readability

# time - date, trim extra spaces with xargs
CLOCK=$(date "+%H:%M:%S" 2>&1)

# system load
LOAD=$(uptime 2>&1 | awk '{ print $8,$9,$10 }' 2>&1 |
  grep -E "[0-9]+.[0-9]+, [0-9]+.[0-9]+, [0-9]+.[0-9]+" 2>&1 | tr -d ',' 2>&1)

# cpu temp, celcius, fahrenheit, (raspberry pi)
CPU_CTEMP=$(</sys/class/thermal/thermal_zone0/temp)
CPU_CTEMP=$(echo "$CPU_CTEMP / 100 * 0.1" 2>&1 |
  bc 2>&1 | awk '{ printf "%.0f\n", $1 }' 2>&1)
CPU_FTEMP=$(echo "(1.8 * $CPU_CTEMP) + 32" 2>&1 |
  bc 2>&1 | awk '{ printf "%.0f\n", $1 }' 2>&1)

# free Memory
FREE_MEM=$(free --mega 2>/dev/null | grep "Mem" 2>/dev/null |
  awk '{ print $4 }' 2>/dev/null)
# total Memory
TOTAL_MEM=$(free --mega 2>/dev/null | grep "Mem" 2>/dev/null |
  awk '{ print $2 }' 2>/dev/null)

# free Space, mmc block device #0, partition #2, partition #2, dev/root
USED_HDD=$(df -h 2>/dev/null | grep -E "mmcblk0p2|mmcblk0p3|/dev/root" 2>/dev/null |
  awk '{ print $3 }' 2>/dev/null)
USED_HDD_P=$(df -h | grep -E "mmcblk0p2|mmcblk0p3|/dev/root" 2>/dev/null |
  awk '{ print $5 }' 2>/dev/null)

# get interface
IFCONFIG=$(ifconfig 2>/dev/null | grep -E "wlan*|eth*" 2>/dev/null)
INTERFACE=$(echo "$IFCONFIG" 2>/dev/null | grep -E "wlan*|eth*" 2>/dev/null |
  awk '{ print $1 }' 2>/dev/null | awk -F: '{ print $1 }' 2>/dev/null |
  head -1 2>/dev/null)
