#!/bin/bash

# By Rainman
# V20222508
# 0.5.1.6

source /usr/local/bin/include/pinode/pinode.conf 2>&1

### auto graphs w time #########################################################

if [[ $(echo "$GRAPH_TIME" 2>&1 | egrep "A|Auto|a|auto|0" 2>&1) ]] &>/dev/null; then

  # uptime in hours
  echo "$(cat "${LOG_DIR:?}"/node_data/wallet/uptime 2>/dev/null)/3600" 2>&1 | bc >"${LOG_DIR:?}"/node_data/wallet/uptime.hours 2>&1
  ROUND_UP=$(cat "${LOG_DIR:?}"/node_data/wallet/uptime.hours 2>/dev/null)
  # organic hour graph ruled by uptime_daemon > uptime.hours
  if [[ "$ROUND_UP" -eq "0" ]] &>/dev/null; then
    GRAPH_TIME="1h"
  else
    GRAPH_TIME="${ROUND_UP:?}h"
  fi
fi

### create graphs ##############################################################

# loadavg 1,5,15m
rrdtool graph /var/www/html/load_graph.png \
  -w 400 -h 160 -a PNG \
  --slope-mode \
  --vertical-label "System Load" \
  --color BACK#565875 \
  --color FONT#FFFFFF \
  --color CANVAS#42445F \
  --color GRID#565875 \
  --color FRAME#565875 \
  --color SHADEA#565875 \
  --color SHADEB#565875 \
  --end now --start end-"${GRAPH_TIME:?}" \
  DEF:load=/home/"$(whoami)"/stats/load.rrd:load:MAX \
  DEF:load5=/home/"$(whoami)"/stats/load5.rrd:load5:MAX \
  DEF:load15=/home/"$(whoami)"/stats/load15.rrd:load15:MAX \
  GPRINT:load:LAST:%.2lf \
  GPRINT:load5:LAST:%.2lf \
  GPRINT:load15:LAST:%.2lf \
  LINE1:load#45DC63:"Load 1m" \
  LINE2:load5#FFE000:"Load 5m" \
  LINE2:load15#FF5100:"Load 15m"

# inputs
rrdtool graph /var/www/html/inputs_graph.png \
  -w 400 -h 160 -a PNG \
  --slope-mode \
  --vertical-label "Wallet Inputs" \
  --alt-autoscale-max --lower-limit=1 \
  --color BACK#565875 \
  --color FONT#FFFFFF \
  --color CANVAS#42445F \
  --color GRID#565875 \
  --color FRAME#565875 \
  --color SHADEA#565875 \
  --color SHADEB#565875 \
  --end now --start end-"${GRAPH_TIME:?}" \
  DEF:inputs=/home/"$(whoami)"/stats/inputs.rrd:inputs:MAX \
  GPRINT:inputs:LAST:%.0lf\ Now \
  GPRINT:inputs:MAX:%.0lf\ Max \
  GPRINT:inputs:MIN:%.0lf\ Min \
  AREA:inputs#819C7D:"Inputs"

# peers
rrdtool graph /var/www/html/peers_graph.png \
  -w 400 -h 160 -a PNG \
  --slope-mode \
  --vertical-label "Peers (P2P)" \
  --alt-autoscale-max --lower-limit=1 \
  --color BACK#565875 \
  --color FONT#FFFFFF \
  --color CANVAS#42445F \
  --color GRID#565875 \
  --color FRAME#565875 \
  --color SHADEA#565875 \
  --color SHADEB#565875 \
  --end now --start end-"${GRAPH_TIME:?}" \
  DEF:peers=/home/"$(whoami)"/stats/peers.rrd:peers:MAX \
  DEF:peers=/home/"$(whoami)"/stats/peers.rrd:peers:AVERAGE \
  DEF:banned_peers=/home/"$(whoami)"/stats/banned_peers.rrd:banned_peers:MAX \
  DEF:peers_ipv4=/home/"$(whoami)"/stats/peers_proto.rrd:peers_ipv4:MAX \
  DEF:peers_ipv6=/home/"$(whoami)"/stats/peers_proto.rrd:peers_ipv6:MAX \
  DEF:peers_dns=/home/"$(whoami)"/stats/peers_proto.rrd:peers_dns:MAX \
  DEF:peers_onion=/home/"$(whoami)"/stats/peers_proto.rrd:peers_onion:MAX \
  DEF:peers_proxy=/home/"$(whoami)"/stats/peers_proto.rrd:peers_proxy:MAX \
  GPRINT:peers:LAST:%.0lf\ Now \
  GPRINT:peers:AVERAGE:%.0lf\ AVG \
  GPRINT:banned_peers:LAST:%.0lf\ Bans \
  GPRINT:peers:MAX:%.0lf\ Max \
  GPRINT:peers:MIN:%.0lf\ Min \
  LINE2:peers#82FE82:"Peers" \
  LINE1:banned_peers#CC2C4B:"Bans" \
  LINE1:peers_ipv4#FFFFFF \
  LINE1:peers_ipv6#2CCC8D \
  LINE1:peers_dns#2C69CC \
  LINE1:peers_onion#A02CCC \
  LINE1:peers_proxy#C26EE2

# blockchain activity
rrdtool graph /var/www/html/blockchain_activity.png \
  -w 1394 -h 100 -a PNG \
  --slope-mode \
  --vertical-label "Activity" \
  --alt-autoscale-max --lower-limit=1 \
  --color BACK#565875 \
  --color FONT#FFFFFF \
  --color CANVAS#42445F \
  --color GRID#565875 \
  --color FRAME#565875 \
  --color SHADEA#565875 \
  --color SHADEB#565875 \
  --end now --start end-"${GRAPH_TIME:?}" \
  DEF:activity=/home/"$(whoami)"/stats/block_activity.rrd:activity:MAX \
  GPRINT:activity:LAST:%.2lf\ Now \
  GPRINT:activity:AVERAGE:%.2lf\ AVG \
  GPRINT:activity:MAX:%.2lf\ Max \
  GPRINT:activity:MIN:%.2lf\ Min \
  AREA:activity#71E75E:"Activity"

# masternodes
rrdtool graph /var/www/html/masternode_count_graph.png \
  -w 1394 -h 100 -a PNG \
  --slope-mode \
  --vertical-label "Masternodes" \
  --alt-autoscale-max --lower-limit=1 \
  --color BACK#565875 \
  --color FONT#FFFFFF \
  --color CANVAS#42445F \
  --color GRID#565875 \
  --color FRAME#565875 \
  --color SHADEA#565875 \
  --color SHADEB#565875 \
  --end now --start end-"${GRAPH_TIME:?}" \
  DEF:total=/home/"$(whoami)"/stats/masternodes.rrd:total:MAX \
  DEF:stable=/home/"$(whoami)"/stats/masternodes.rrd:stable:MAX \
  DEF:enabled=/home/"$(whoami)"/stats/masternodes.rrd:enabled:MAX \
  DEF:inqueue=/home/"$(whoami)"/stats/masternodes.rrd:inqueue:MAX \
  GPRINT:total:LAST:%.0lf\ Total \
  GPRINT:stable:LAST:%.0lf\ Stable \
  GPRINT:enabled:LAST:%.0lf\ Enabled \
  GPRINT:inqueue:LAST:%.0lf\ Inqueue \
  LINE2:total#F4F4F4:"Total" \
  LINE1:stable#3BE536:"Stable" \
  LINE1:enabled#3bbb33:"Enabled" \
  LINE1:inqueue#828282:"Inqueue"

# masternode pay
rrdtool graph /var/www/html/masternode_pay_graph.png \
  -w 1394 -h 100 -a PNG \
  --slope-mode \
  --vertical-label "Masternode Earnings" \
  --alt-autoscale-max --lower-limit=1 \
  --color BACK#565875 \
  --color FONT#FFFFFF \
  --color CANVAS#42445F \
  --color GRID#565875 \
  --color FRAME#565875 \
  --color SHADEA#565875 \
  --color SHADEB#565875 \
  --end now --start end-"${GRAPH_TIME:?}" \
  DEF:paycount=/home/"$(whoami)"/stats/masternode_pay.rrd:paycount:MAX \
  DEF:payout=/home/"$(whoami)"/stats/masternode_pay.rrd:payout:MAX \
  DEF:payvalue=/home/"$(whoami)"/stats/masternode_pay.rrd:payvalue:MAX \
  GPRINT:paycount:LAST:%.2lf\ Rewards\ Daily \
  GPRINT:payout:LAST:%.2lf\ Coins\ Daily \
  GPRINT:payvalue:LAST:%.2lf\ USD\ Daily \
  LINE1:paycount#FFDC77:"Rewards Daily" \
  LINE1:payout#85bb65:"Coins Daily" \
  LINE2:payvalue#668163:"USD Daily"

# plural
REW_GPRINT="Rewards"
POS_GPRINT="Stakes"

# single reward
if [[ "$(wc -l "${DATA_DIR:?}"/rewards 2>&1 | awk '{ print $1 }' 2>&1)" -eq "1" ]] &>/dev/null; then
  REW_GPRINT="Reward"
fi
# single stake
if [[ "$(wc -l "${DATA_DIR:?}"/staking 2>&1 | awk '{ print $1 }' 2>&1)" -eq "1" ]] &>/dev/null; then
  POS_GPRINT="Stake"
fi

# masternode successfully started, continue
if [[ "$(grep "successfully started" "${DATA_DIR:?}"/masternode_status)" ]] &>/dev/null; then
  # stakes & rewards
  rrdtool graph /var/www/html/stakes_and_rewards_graph.png \
    -w 400 -h 160 -a PNG \
    --slope-mode \
    --vertical-label "Stakes & Rewards" \
    --alt-autoscale-max --lower-limit=1 \
    --color BACK#565875 \
    --color FONT#FFFFFF \
    --color CANVAS#42445F \
    --color GRID#565875 \
    --color FRAME#565875 \
    --color SHADEA#565875 \
    --color SHADEB#565875 \
    --end now --start end-"${GRAPH_TIME:?}" \
    DEF:stakes=/home/"$(whoami)"/stats/stakes.rrd:stakes:MAX \
    DEF:paycount=/home/"$(whoami)"/stats/masternode_pay.rrd:paycount:MAX \
    GPRINT:paycount:LAST:%.2lf\ "${REW_GPRINT:?}" \
    GPRINT:stakes:LAST:%.0lf\ "${POS_GPRINT:?}" \
    GPRINT:stakes:AVERAGE:%.0lf\ PoS\ AVG \
    AREA:paycount#779CFF \
    LINE2:stakes#FFDC77:"Stakes"
else
  rrdtool graph /var/www/html/stakes_and_rewards_graph.png \
    -w 400 -h 160 -a PNG \
    --slope-mode \
    --vertical-label "Stakes" \
    --alt-autoscale-max --lower-limit=1 \
    --color BACK#565875 \
    --color FONT#FFFFFF \
    --color CANVAS#42445F \
    --color GRID#565875 \
    --color FRAME#565875 \
    --color SHADEA#565875 \
    --color SHADEB#565875 \
    --end now --start end-"${GRAPH_TIME:?}" \
    DEF:stakes=/home/"$(whoami)"/stats/stakes.rrd:stakes:MAX \
    GPRINT:stakes:LAST:%.0lf\ "${POS_GPRINT:?}" \
    GPRINT:stakes:AVERAGE:%.0lf\ PoS\ AVG \
    LINE2:stakes#FFDC77:"Stakes"
fi

# balance
rrdtool graph /var/www/html/balance_graph.png \
  -w 400 -h 160 -a PNG \
  --slope-mode \
  --vertical-label "Wallet Balance" \
  --alt-autoscale-max --lower-limit=1 \
  --color BACK#565875 \
  --color FONT#FFFFFF \
  --color CANVAS#42445F \
  --color GRID#565875 \
  --color FRAME#565875 \
  --color SHADEA#565875 \
  --color SHADEB#565875 \
  --end now --start end-"${GRAPH_TIME:?}" \
  DEF:balance=/home/"$(whoami)"/stats/balance.rrd:balance:MAX \
  DEF:value=/home/"$(whoami)"/stats/value.rrd:value:MAX \
  GPRINT:balance:LAST:%.2lf\ Coins \
  GPRINT:value:LAST:%.2lf\ USD \
  AREA:balance#85bb65:"Balance" \
  LINE2:value#668163:"USD"

# rank
rrdtool graph /var/www/html/rank_graph.png \
  -w 400 -h 160 -a PNG \
  --slope-mode \
  --vertical-label "CoinMarketCap Rank" \
  --alt-autoscale-max --lower-limit=1 \
  --color BACK#565875 \
  --color FONT#FFFFFF \
  --color CANVAS#42445F \
  --color GRID#565875 \
  --color FRAME#565875 \
  --color SHADEA#565875 \
  --color SHADEB#565875 \
  --end now --start end-"${GRAPH_TIME:?}" \
  DEF:rank=/home/"$(whoami)"/stats/rank.rrd:rank:MAX \
  DEF:rank=/home/"$(whoami)"/stats/rank.rrd:rank:AVERAGE \
  GPRINT:rank:LAST:%.0lf\ Rank \
  GPRINT:rank:AVERAGE:%.0lf\ Rank\ AVG \
  LINE1:rank#8A8FAB:"Rank"

# watchlist
rrdtool graph /var/www/html/watchlist_graph.png \
  -w 400 -h 150 -a PNG \
  --slope-mode \
  --vertical-label "CoinMarketCap Watchlist" \
  --alt-autoscale-max --lower-limit=1 \
  --color BACK#565875 \
  --color FONT#FFFFFF \
  --color CANVAS#42445F \
  --color GRID#565875 \
  --color FRAME#565875 \
  --color SHADEA#565875 \
  --color SHADEB#565875 \
  --end now --start end-"${GRAPH_TIME:?}" \
  DEF:watchlist=/home/"$(whoami)"/stats/watchlist.rrd:watchlist:MAX \
  DEF:watchlist=/home/"$(whoami)"/stats/watchlist.rrd:watchlist:AVERAGE \
  GPRINT:watchlist:LAST:%.0lf\ Watchlist \
  GPRINT:watchlist:AVERAGE:%.0lf\ Watchlist\ AVG \
  LINE1:watchlist#65AABB:"Watchlist"

# market price
rrdtool graph /var/www/html/market_price_graph.png \
  -w 400 -h 150 -a PNG \
  --slope-mode \
  --vertical-label "Market Price" \
  --alt-autoscale-max --lower-limit=1 \
  --color BACK#565875 \
  --color FONT#FFFFFF \
  --color CANVAS#42445F \
  --color GRID#565875 \
  --color FRAME#565875 \
  --color SHADEA#565875 \
  --color SHADEB#565875 \
  --end now --start end-"${GRAPH_TIME:?}" \
  DEF:price_cg=/home/"$(whoami)"/stats/coingecko.rrd:price_cg:MAX \
  DEF:price_cmc=/home/"$(whoami)"/stats/coinmarketcap.rrd:price_cmc:MAX \
  DEF:price_avg=/home/"$(whoami)"/stats/price_avg.rrd:price_avg:MAX \
  GPRINT:price_cg:LAST:%.4lf\ CoinGecko\ Price \
  GPRINT:price_cmc:LAST:%.4lf\ CoinMarketCap\ Price \
  LINE1:price_cg#7D7FB4 \
  LINE1:price_cmc#7476A8 \
  LINE3:price_avg#9A9DE1

# market volume
rrdtool graph /var/www/html/market_volume_graph.png \
  -w 400 -h 150 -a PNG \
  --slope-mode \
  --vertical-label "Market Volume" \
  --alt-autoscale-max --lower-limit=1 \
  --color BACK#565875 \
  --color FONT#FFFFFF \
  --color CANVAS#42445F \
  --color GRID#565875 \
  --color FRAME#565875 \
  --color SHADEA#565875 \
  --color SHADEB#565875 \
  --end now --start end-"${GRAPH_TIME:?}" \
  DEF:volume_cg=/home/"$(whoami)"/stats/coingecko.rrd:volume_cg:MAX \
  DEF:volume_cmc=/home/"$(whoami)"/stats/coinmarketcap.rrd:volume_cmc:MAX \
  DEF:volume_avg=/home/"$(whoami)"/stats/volume_avg.rrd:volume_avg:MAX \
  GPRINT:volume_cg:LAST:%.2lf\ CoinGecko\ Volume \
  GPRINT:volume_cmc:LAST:%.2lf\ CoinMarketCap\ Volume \
  LINE1:volume_cg#7D7FB4 \
  LINE1:volume_cmc#7476A8 \
  LINE3:volume_avg#7C9AC2

# network
rrdtool graph /var/www/html/network_graph.png \
  -w 400 -h 160 -a PNG \
  --slope-mode \
  --vertical-label "Network" \
  --color BACK#565875 \
  --color FONT#FFFFFF \
  --color CANVAS#42445F \
  --color GRID#565875 \
  --color FRAME#565875 \
  --color SHADEA#565875 \
  --color SHADEB#565875 \
  --end now --start end-"${GRAPH_TIME:?}" \
  DEF:rxbytes=/home/"$(whoami)"/stats/network.rrd:rxbytes:MAX \
  DEF:txbytes=/home/"$(whoami)"/stats/network.rrd:txbytes:MAX \
  GPRINT:rxbytes:MAX:%.0lf\ Bytes\ Down \
  GPRINT:txbytes:MAX:%.0lf\ Bytes\ Up \
  LINE1:rxbytes#3DCD3D:"Down" \
  LINE1:txbytes#DC5F3A:"Up"

# total hdd, used
rrdtool graph /var/www/html/hdd_graph.png \
  -w 400 -h 160 -a PNG \
  --slope-mode \
  --vertical-label "System Drive" \
  --alt-autoscale-max --lower-limit=1 \
  --color BACK#565875 \
  --color FONT#FFFFFF \
  --color CANVAS#42445F \
  --color GRID#565875 \
  --color FRAME#565875 \
  --color SHADEA#565875 \
  --color SHADEB#565875 \
  --end now --start end-"${GRAPH_TIME:?}" \
  DEF:hdd_total=/home/"$(whoami)"/stats/hdd_total.rrd:hdd_total:MAX \
  DEF:hdd=/home/"$(whoami)"/stats/hdd.rrd:hdd:MAX \
  GPRINT:hdd_total:LAST:%.2lf\ GB \
  GPRINT:hdd:LAST:%.2lf\ GB \
  AREA:hdd_total#8AA6B6:"Total Space" \
  AREA:hdd#597E93:"Used Space"

# memory
rrdtool graph /var/www/html/memory_graph.png \
  -w 400 -h 160 -a PNG \
  --slope-mode \
  --vertical-label "Memory (MB)" \
  --color BACK#565875 \
  --color FONT#FFFFFF \
  --color CANVAS#42445F \
  --color GRID#565875 \
  --color FRAME#565875 \
  --color SHADEA#565875 \
  --color SHADEB#565875 \
  --end now --start end-"${GRAPH_TIME:?}" \
  DEF:memory_total=/home/"$(whoami)"/stats/memory_total.rrd:memory_total:MAX \
  DEF:memory_free=/home/"$(whoami)"/stats/memory_free.rrd:memory_free:MAX \
  GPRINT:memory_total:MAX:%.2lf\M\ Total \
  GPRINT:memory_free:LAST:%.2lf\M\ Free \
  AREA:memory_total#8BABB6:"Total" \
  AREA:memory_free#9FC49A:"Free"

# cpu temperature
rrdtool graph /var/www/html/temp_graph.png \
  -w 400 -h 160 -a PNG \
  --slope-mode \
  --vertical-label "CPU Temp (°C)" \
  --color BACK#565875 \
  --color FONT#FFFFFF \
  --color CANVAS#42445F \
  --color GRID#565875 \
  --color FRAME#565875 \
  --color SHADEA#565875 \
  --color SHADEB#565875 \
  --end now --start end-"${GRAPH_TIME:?}" \
  DEF:temp=/home/"$(whoami)"/stats/temp.rrd:temp:MAX \
  GPRINT:temp:LAST:%.2lf\°C\ Now \
  GPRINT:temp:AVERAGE:%.2lf\°C\ AVG \
  GPRINT:temp:MAX:%.2lf\°C\ Max \
  GPRINT:temp:MIN:%.2lf\°C\ Min \
  AREA:temp#F15A3A:"CPUTemp"

# auto proof-of-stake config
if [[ "$AUTO_POS" -eq "1" ]] &>/dev/null; then

  # difficulty + auto pos
  rrdtool graph /var/www/html/difficulty_graph.png \
    -w 400 -h 160 -a PNG \
    --slope-mode \
    --vertical-label "Network Difficulty+APC" \
    --alt-autoscale-max --lower-limit=1 \
    --color BACK#565875 \
    --color FONT#FFFFFF \
    --color CANVAS#42445F \
    --color GRID#565875 \
    --color FRAME#565875 \
    --color SHADEA#565875 \
    --color SHADEB#565875 \
    --end now --start end-"${GRAPH_TIME:?}" \
    DEF:difficulty=/home/"$(whoami)"/stats/difficulty.rrd:difficulty:MAX \
    DEF:set_auto_pos=/home/"$(whoami)"/stats/set_auto_pos.rrd:set_auto_pos:MAX \
    GPRINT:difficulty:LAST:%.0lf\ Now \
    GPRINT:set_auto_pos:LAST:%.0lf\ APC \
    GPRINT:difficulty:AVERAGE:%.0lf\ AVG \
    GPRINT:difficulty:MAX:%.0lf\ Max \
    GPRINT:difficulty:MIN:%.0lf\ Min \
    AREA:difficulty#C99999 \
    LINE1:set_auto_pos#FFFFFF

  # total avg confirmations + auto pos
  rrdtool graph /var/www/html/total_tx_graph.png \
    -w 400 -h 160 -a PNG \
    --slope-mode \
    --vertical-label "Wallet Total AVG TX" \
    --alt-autoscale-max --lower-limit=1 \
    --color BACK#565875 \
    --color FONT#FFFFFF \
    --color CANVAS#42445F \
    --color GRID#565875 \
    --color FRAME#565875 \
    --color SHADEA#565875 \
    --color SHADEB#565875 \
    --end now --start end-"${GRAPH_TIME:?}" \
    DEF:total_tx=/home/"$(whoami)"/stats/total_tx.rrd:total_tx:MAX \
    DEF:set_auto_con=/home/"$(whoami)"/stats/set_auto_con.rrd:set_auto_con:MAX \
    GPRINT:total_tx:LAST:%.0lf\ Now \
    GPRINT:set_auto_con:LAST:%.0lf\ APL \
    GPRINT:total_tx:AVERAGE:%.0lf\ AVG \
    GPRINT:total_tx:MAX:%.0lf\ Max \
    GPRINT:total_tx:MIN:%.0lf\ Min \
    AREA:total_tx#3C79A9 \
    LINE1:set_auto_con#FFFFFF

else

  # difficulty normal
  rrdtool graph /var/www/html/difficulty_graph.png \
    -w 400 -h 160 -a PNG \
    --slope-mode \
    --vertical-label "Network Difficulty" \
    --alt-autoscale-max --lower-limit=1 \
    --color BACK#565875 \
    --color FONT#FFFFFF \
    --color CANVAS#42445F \
    --color GRID#565875 \
    --color FRAME#565875 \
    --color SHADEA#565875 \
    --color SHADEB#565875 \
    --end now --start end-"${GRAPH_TIME:?}" \
    DEF:difficulty=/home/"$(whoami)"/stats/difficulty.rrd:difficulty:MAX \
    GPRINT:difficulty:LAST:%.0lf\ Now \
    GPRINT:difficulty:AVERAGE:%.0lf\ AVG \
    GPRINT:difficulty:MAX:%.0lf\ Max \
    GPRINT:difficulty:MIN:%.0lf\ Min \
    AREA:difficulty#C99999:"Network Difficulty"

  # total avg confirmations normal
  rrdtool graph /var/www/html/total_tx_graph.png \
    -w 400 -h 160 -a PNG \
    --slope-mode \
    --vertical-label "Wallet Total AVG TX" \
    --alt-autoscale-max --lower-limit=1 \
    --color BACK#565875 \
    --color FONT#FFFFFF \
    --color CANVAS#42445F \
    --color GRID#565875 \
    --color FRAME#565875 \
    --color SHADEA#565875 \
    --color SHADEB#565875 \
    --end now --start end-"${GRAPH_TIME:?}" \
    DEF:total_tx=/home/"$(whoami)"/stats/total_tx.rrd:total_tx:MAX \
    GPRINT:total_tx:LAST:%.0lf\ Now \
    GPRINT:total_tx:AVERAGE:%.0lf\ AVG \
    GPRINT:total_tx:MAX:%.0lf\ Max \
    GPRINT:total_tx:MIN:%.0lf\ Min \
    AREA:total_tx#3C79A9
fi

# END
