#!/bin/bash

# By Rainman
# V20222001
# 0.2.6.6

source /home/pi/pitrump.conf

### auto graphs w time #########################################################

if [[ $(echo "$GRAPH_TIME" 2>&1 | egrep "A|Auto|a|auto|0" 2>&1) ]] &>/dev/null; then

  # uptime in hours
  echo "$(cat "${LOG_DIR:?}"/node_data/uptime 2>/dev/null)/3600" 2>&1 | bc >"${LOG_DIR:?}"/node_data/uptime.hours 2>&1
  ROUND_UP=$(cat "${LOG_DIR:?}"/node_data/uptime.hours 2>/dev/null)
  # organic hour graph ruled by uptime_daemon > uptime.hours
  if [[ "$ROUND_UP" -eq "0" ]] &>/dev/null; then
    GRAPH_TIME="1h"
  else
    GRAPH_TIME="${ROUND_UP:?}h"
  fi
fi

### create graphs ##############################################################

# loadavg 1,5,15m (24hour)
rrdtool graph /var/www/html/load_graph.png \
  -w 400 -h 164 -a PNG \
  --slope-mode \
  --vertical-label "System Load" \
  --color BACK#565875 \
  --color FONT#FFFFFF \
  --color CANVAS#42445F \
  --color GRID#565875 \
  --color FRAME#565875 \
  --color SHADEA#565875 \
  --color SHADEB#565875 \
  --end now --start end-"${GRAPH_TIME:?}" \
  DEF:load=/home/"$(whoami)"/stats/load.rrd:load:MAX \
  DEF:load5=/home/"$(whoami)"/stats/load5.rrd:load5:MAX \
  DEF:load15=/home/"$(whoami)"/stats/load15.rrd:load15:MAX \
  GPRINT:load:LAST:%.2lf \
  GPRINT:load5:AVERAGE:%.2lf \
  GPRINT:load15:AVERAGE:%.2lf \
  AREA:load#45DC63:"Load 1m" \
  LINE2:load5#FFE000:"Load 5m" \
  LINE2:load15#FF5100:"Load 15m"

# inputs (24hour)
rrdtool graph /var/www/html/inputs_graph.png \
  -w 400 -h 164 -a PNG \
  --slope-mode \
  --vertical-label "Wallet Inputs" \
  --alt-autoscale-max --lower-limit=1 \
  --color BACK#565875 \
  --color FONT#FFFFFF \
  --color CANVAS#42445F \
  --color GRID#565875 \
  --color FRAME#565875 \
  --color SHADEA#565875 \
  --color SHADEB#565875 \
  --end now --start end-"${GRAPH_TIME:?}" \
  DEF:inputs=/home/"$(whoami)"/stats/inputs.rrd:inputs:MAX \
  GPRINT:inputs:LAST:%.0lf\ Now \
  GPRINT:inputs:MAX:%.0lf\ Max \
  GPRINT:inputs:MIN:%.0lf\ Min \
  AREA:inputs#819C7D:"Inputs"

# peers (24hour)
rrdtool graph /var/www/html/peers_graph.png \
  -w 400 -h 164 -a PNG \
  --slope-mode \
  --vertical-label "Peers (P2P)" \
  --alt-autoscale-max --lower-limit=1 \
  --color BACK#565875 \
  --color FONT#FFFFFF \
  --color CANVAS#42445F \
  --color GRID#565875 \
  --color FRAME#565875 \
  --color SHADEA#565875 \
  --color SHADEB#565875 \
  --end now --start end-"${GRAPH_TIME:?}" \
  DEF:peers=/home/"$(whoami)"/stats/peers.rrd:peers:MAX \
  GPRINT:peers:LAST:%.0lf\ Now \
  GPRINT:peers:AVERAGE:%.0lf\ AVG \
  GPRINT:peers:MAX:%.0lf\ Max \
  GPRINT:peers:MIN:%.0lf\ Min \
  AREA:peers#A28DB8:"Peers"

# stakes (24hour)
rrdtool graph /var/www/html/stakes_graph.png \
  -w 400 -h 164 -a PNG \
  --slope-mode \
  --vertical-label "Wallet Stakes" \
  --alt-autoscale-max --lower-limit=1 \
  --color BACK#565875 \
  --color FONT#FFFFFF \
  --color CANVAS#42445F \
  --color GRID#565875 \
  --color FRAME#565875 \
  --color SHADEA#565875 \
  --color SHADEB#565875 \
  --end now --start end-"${GRAPH_TIME:?}" \
  DEF:stakes=/home/"$(whoami)"/stats/stakes.rrd:stakes:MAX \
  GPRINT:stakes:LAST:%.0lf\ Now \
  GPRINT:stakes:AVERAGE:%.0lf\ AVG \
  GPRINT:stakes:MAX:%.0lf\ Max \
  GPRINT:stakes:MIN:%.0lf\ Min \
  AREA:stakes#FFB777:"Stakes"

# balance (24hour)
rrdtool graph /var/www/html/balance_graph.png \
  -w 400 -h 164 -a PNG \
  --slope-mode \
  --vertical-label "Wallet Balance" \
  --alt-autoscale-max --lower-limit=1 \
  --color BACK#565875 \
  --color FONT#FFFFFF \
  --color CANVAS#42445F \
  --color GRID#565875 \
  --color FRAME#565875 \
  --color SHADEA#565875 \
  --color SHADEB#565875 \
  --end now --start end-"${GRAPH_TIME:?}" \
  DEF:balance=/home/"$(whoami)"/stats/balance.rrd:balance:MAX \
  DEF:value=/home/"$(whoami)"/stats/value.rrd:value:MAX \
  GPRINT:balance:LAST:%.2lf\ Trump \
  GPRINT:value:LAST:%.2lf\ USD \
  AREA:balance#85bb65:"Balance" \
  LINE2:value#668163:"USD"

# network (24hour)
rrdtool graph /var/www/html/network_graph.png \
  -w 400 -h 164 -a PNG \
  --slope-mode \
  --vertical-label "Network" \
  --color BACK#565875 \
  --color FONT#FFFFFF \
  --color CANVAS#42445F \
  --color GRID#565875 \
  --color FRAME#565875 \
  --color SHADEA#565875 \
  --color SHADEB#565875 \
  --end now --start end-"${GRAPH_TIME:?}" \
  DEF:rxbytes=/home/"$(whoami)"/stats/network.rrd:rxbytes:MAX \
  DEF:txbytes=/home/"$(whoami)"/stats/network.rrd:txbytes:MAX \
  DEF:rxbytes=/home/"$(whoami)"/stats/network.rrd:rxbytes:MAX \
  DEF:txbytes=/home/"$(whoami)"/stats/network.rrd:txbytes:MAX \
  GPRINT:rxbytes:MAX:%.0lf\ Bytes\ Down \
  GPRINT:txbytes:MAX:%.0lf\ Bytes\ Up \
  LINE1:rxbytes#3DCD3D:"Down" \
  LINE1:txbytes#DC5F3A:"Up"

# total hdd, used (24hour)
rrdtool graph /var/www/html/hdd_graph.png \
  -w 400 -h 164 -a PNG \
  --slope-mode \
  --vertical-label "System Drive" \
  --alt-autoscale-max --lower-limit=1 \
  --color BACK#565875 \
  --color FONT#FFFFFF \
  --color CANVAS#42445F \
  --color GRID#565875 \
  --color FRAME#565875 \
  --color SHADEA#565875 \
  --color SHADEB#565875 \
  --end now --start end-"${GRAPH_TIME:?}" \
  DEF:hdd_total=/home/"$(whoami)"/stats/hdd_total.rrd:hdd_total:MAX \
  DEF:hdd=/home/"$(whoami)"/stats/hdd.rrd:hdd:MAX \
  GPRINT:hdd_total:LAST:%.2lf\ GB \
  GPRINT:hdd:LAST:%.2lf\ GB \
  AREA:hdd_total#8AA6B6:"Total Space" \
  AREA:hdd#597E93:"Used Space"

# memory (24hour)
rrdtool graph /var/www/html/memory_graph.png \
  -w 400 -h 164 -a PNG \
  --slope-mode \
  --vertical-label "Memory (MB)" \
  --color BACK#565875 \
  --color FONT#FFFFFF \
  --color CANVAS#42445F \
  --color GRID#565875 \
  --color FRAME#565875 \
  --color SHADEA#565875 \
  --color SHADEB#565875 \
  --end now --start end-"${GRAPH_TIME:?}" \
  DEF:memory_total=/home/"$(whoami)"/stats/memory_total.rrd:memory_total:MAX \
  DEF:memory_free=/home/"$(whoami)"/stats/memory_free.rrd:memory_free:MAX \
  GPRINT:memory_total:MAX:%.2lf\M\ Total \
  GPRINT:memory_free:LAST:%.2lf\M\ Free \
  AREA:memory_total#8BABB6:"Total" \
  AREA:memory_free#9FC49A:"Free"

# cpu temperature (24hour)
rrdtool graph /var/www/html/temp_graph.png \
  -w 400 -h 164 -a PNG \
  --slope-mode \
  --vertical-label "CPU Temp (°C)" \
  --color BACK#565875 \
  --color FONT#FFFFFF \
  --color CANVAS#42445F \
  --color GRID#565875 \
  --color FRAME#565875 \
  --color SHADEA#565875 \
  --color SHADEB#565875 \
  --end now --start end-"${GRAPH_TIME:?}" \
  DEF:temp=/home/"$(whoami)"/stats/temp.rrd:temp:MAX \
  GPRINT:temp:LAST:%.2lf\°C\ Now \
  GPRINT:temp:AVERAGE:%.2lf\°C\ AVG \
  GPRINT:temp:MAX:%.2lf\°C\ Max \
  GPRINT:temp:MIN:%.2lf\°C\ Min \
  AREA:temp#F15A3A:"CPUTemp"

# difficulty (24hour)
rrdtool graph /var/www/html/difficulty_graph.png \
  -w 1394 -h 142 -a PNG \
  --slope-mode \
  --vertical-label "Network Difficulty+APC" \
  --alt-autoscale-max --lower-limit=1 \
  --color BACK#565875 \
  --color FONT#FFFFFF \
  --color CANVAS#42445F \
  --color GRID#565875 \
  --color FRAME#565875 \
  --color SHADEA#565875 \
  --color SHADEB#565875 \
  --end now --start end-"${GRAPH_TIME:?}" \
  DEF:difficulty=/home/"$(whoami)"/stats/difficulty.rrd:difficulty:MAX \
  DEF:set_auto_pos=/home/"$(whoami)"/stats/set_auto_pos.rrd:set_auto_pos:MAX \
  GPRINT:difficulty:LAST:%.0lf\ Now \
  GPRINT:set_auto_pos:LAST:%.0lf\ APC \
  GPRINT:difficulty:AVERAGE:%.0lf\ AVG \
  GPRINT:difficulty:MAX:%.0lf\ Max \
  GPRINT:difficulty:MIN:%.0lf\ Min \
  AREA:difficulty#C99999:"Network Difficulty" \
  LINE1:set_auto_pos#FFFFFF:"Auto PoS Config"

# total avg confirmations (24hour)
rrdtool graph /var/www/html/total_tx_graph.png \
  -w 1394 -h 142 -a PNG \
  --slope-mode \
  --vertical-label "Wallet Total AVG TX" \
  --alt-autoscale-max --lower-limit=1 \
  --color BACK#565875 \
  --color FONT#FFFFFF \
  --color CANVAS#42445F \
  --color GRID#565875 \
  --color FRAME#565875 \
  --color SHADEA#565875 \
  --color SHADEB#565875 \
  --end now --start end-"${GRAPH_TIME:?}" \
  DEF:total_tx=/home/"$(whoami)"/stats/total_tx.rrd:total_tx:MAX \
  DEF:total_tx_q=/home/"$(whoami)"/stats/total_tx_q.rrd:total_tx_q:MAX \
  DEF:set_auto_con=/home/"$(whoami)"/stats/set_auto_con.rrd:set_auto_con:MAX \
  GPRINT:total_tx:LAST:%.0lf\ Now \
  GPRINT:total_tx_q:LAST:%.0lf\ APL \Real \
  GPRINT:set_auto_con:LAST:%.0lf\ APLQ \
  GPRINT:total_tx:AVERAGE:%.0lf\ AVG \
  GPRINT:total_tx:MAX:%.0lf\ Max \
  GPRINT:total_tx:MIN:%.0lf\ Min \
  AREA:total_tx#3C79A9:"AVG Confirmations" \
  LINE1:set_auto_con#FFFFFF:"Auto PoS Limit Q" \
  LINE1:total_tx_q#72B4E9:"Auto PoS Limit (Real)"

# END
