#!/bin/bash

# By Rainman
# V20213012
# 0.0.3.9

source /home/pi/pitrump.conf

# dependencies

# make sure screen is installed
if ! [ -x "$(command -v screen)" ] &>/dev/null; then
  sudo apt-get install screen -y
fi
# make sure tor is installed
if ! [ -x "$(command -v tor)" ] &>/dev/null; then
  sudo apt-get install tor -y
  echo "Setup tor/wallet configurations!"
fi

clear
# look for screen session, if found, killall
if screen -list 2>&1 |
  grep -q "add_peers" &>/dev/null; then
  killall screen &>/dev/null
fi
# install/update
mkdir "${LOG_DIR:?}"/node_data &>/dev/null
sudo mkdir /usr/local/bin/include &>/dev/null
sudo cp -R /home/"$(whoami)"/trump-node/include/* /usr/local/bin/include/ 2>&1
sudo cp -R /home/"$(whoami)"/trump-node/pitrump /usr/local/bin/ 2>&1
sudo cp -R /home/"$(whoami)"/trump-node/include/update /usr/local/bin/ 2>&1
sudo chmod +x /usr/local/bin/update
sudo chown -R "$(whoami)":"$(whoami)" /usr/local/bin/pitrump /usr/local/bin/update /usr/local/bin/include /usr/local/bin/include/* 2>&1
sudo chown "$(whoami)":"$(whoami)" "${LOG_DIR:?}"/node_data 2>&1
echo "Updated! [$(cd /home/"$(whoami)"/trump-node || exit && git rev-parse --short HEAD 2>&1 | grep -Eo '[a0-z9]{7}' 2>&1 | head -1 2>&1)]"
ls -lS /usr/local/bin/include/

# END
