#!/bin/bash

# By Rainman
# V20220101
# 0.0.4.3

# make sure dialog exist
if ! [ -x "$(command -v dialog)" ]; then
  sudo apt-get install dialog -y
fi

HEIGHT=10
WIDTH=40
CHOICE_HEIGHT=2
BACKTITLE="Trump-Node"
TITLE="Node Options"
MENU="Choose one of the following options:"

OPTIONS=(1 "Turn off node")

CHOICE=$(dialog --clear \
  --backtitle "$BACKTITLE" \
  --title "$TITLE" \
  --menu "$MENU" \
  $HEIGHT $WIDTH $CHOICE_HEIGHT \
  "${OPTIONS[@]}" \
  2>&1 >/dev/tty)

clear
case $CHOICE in

"1")

  printf '%b' "[YN] Turn off node, are you sure? y/n \n" -n 1 -r
  if [[ $REPLY =~ ^[Yy]$ ]]; then
    kill "$(pidof trumpcoind)" && sleep 3 && sudo reboot
  fi

  ;;

esac

# END
