#!/bin/bash

# By Rainman
# V20211712
# 0.1.0.4

source /usr/local/bin/include/color

# non responsive
if [[ -z "$IP_ADDRESS" ]] &>/dev/null; then
  IP_ADDRESS="${GR:?}0.0.0.0${N0:?}"
fi
if [[ "$IP_ADDRESS" -eq "0" ]] &>/dev/null; then
  IP_ADDRESS="${GR:?}0.0.0.0${N0:?}"
fi
if [[ "$WALLET_VERSION" -eq "0" ]] &>/dev/null; then
  WALLET_VERSION="${GR:?}0.0.0.0${N0:?}"
fi
if [[ -z "$WALLET_VERSION" ]] &>/dev/null; then
  WALLET_VERSION="${GR:?}0.0.0.0${N0:?}"
fi
if [[ -z "$WALLET_CHAIN" ]] &>/dev/null; then
  WALLET_CHAIN="${GR:?}0${N0:?}"
fi
if [[ -z "$WALLET_HEADS" ]] &>/dev/null; then
  WALLET_HEADS="${GR:?}0${N0:?}"
fi
if [[ -z "$WALLET_BLOCK" ]] &>/dev/null; then
  WALLET_BLOCK="${GR:?}0${N0:?}"
fi
if [[ -z "$WALLET_PEERS_TOTAL" ]] &>/dev/null; then
  WALLET_PEERS_TOTAL="${GR:?}0${N0:?}"
fi
if [[ -z "$WALLET_PEERS_LATEST" ]] &>/dev/null; then
  WALLET_PEERS_LATEST="${GR:?}0${N0:?}"
fi
if [[ -z "$WALLET_PEERS_OTHER" ]] &>/dev/null; then
  WALLET_PEERS_OTHER="${GR:?}0${N0:?}"
fi
if [[ "$WALLET_PEERS_TOTAL" -eq "0" ]] &>/dev/null; then
  WALLET_PEERS_TOTAL="${GR:?}0${N0:?}"
fi
if [[ "$WALLET_PEERS_LATEST" -eq "0" ]] &>/dev/null; then
  WALLET_PEERS_LATEST="${GR:?}0${N0:?}"
fi
if [[ "$WALLET_PEERS_OTHER" -eq "0" ]] &>/dev/null; then
  WALLET_PEERS_OTHER="${GR:?}0${N0:?}"
fi
if [[ -z "$WALLET_BALANCE" ]] &>/dev/null; then
  WALLET_BALANCE="${GR:?}0.00${N0:?}"
fi
if [[ "$WALLET_BALANCE" -eq "0" ]] &>/dev/null; then
  WALLET_BALANCE="${GR:?}0.00${N0:?}"
fi
if [[ "$WALLET_VALUE" -eq "0" ]] &>/dev/null; then
  WALLET_VALUE="${GR:?}0.00${N0:?}"
fi
if [[ -z "$WALLET_VALUE" ]] &>/dev/null; then
  WALLET_VALUE="${GR:?}0.00${N0:?}"
fi
if [[ -z "$WALLET_MEMPOOL" ]] &>/dev/null; then
  WALLET_MEMPOOL="${GR:?}0${N0:?}"
fi
if [[ -z "$WALLET_TXCOUNT" ]] &>/dev/null; then
  WALLET_TXCOUNT="${GR:?}0${N0:?}"
fi
if [[ -z "$WALLET_INPUTS" ]] &>/dev/null; then
  WALLET_INPUTS="${GR:?}0${N0:?}"
fi
if [[ "$WALLET_INPUTS" -eq "0" ]] &>/dev/null; then
  WALLET_INPUTS="${GR:?}0${N0:?}"
fi
if [[ -z "$WALLET_STAKES" ]] &>/dev/null; then
  WALLET_STAKES="${GR:?}0${N0:?}"
fi
if [[ -z "$TIMELINE" ]] &>/dev/null; then
  TIMELINE="${N0:?}"
fi
if [[ -z "$POS_STATUS" ]] &>/dev/null; then
  POS_STATUS="${GR:?}S${GR:?}"
fi
if [[ "$POS_STATUS" -eq "0" ]] &>/dev/null; then
  POS_STATUS="${GR:?}S${GR:?}"
fi
if [[ -z "$DARKMODE" ]] &>/dev/null; then
  DARKMODE="${GR:?}0${GR:?}"
fi
if [[ "$DARKMODE" -eq "0" ]] &>/dev/null; then
  DARKMODE="${GR:?}0${GR:?}"
fi
if [[ -z "$SUCCESS_RA_SX" ]] &>/dev/null; then
  SUCCESS_RA_SX="0"
fi
if [[ "$SUCCESS_RA_SX" -eq "0" ]] &>/dev/null; then
  SUCCESS_RA_SX="0"
fi
if [[ -z "$PEERS_TRIES" ]] &>/dev/null; then
  PEERS_TRIES="0"
fi
if [[ "$PEERS_TRIES" -eq "0" ]] &>/dev/null; then
  PEERS_TRIES="0"
fi

# END
