#!/bin/bash

# By Rainman
# V20211212
# 0.1.0.1

source /usr/local/bin/include/color

# non responsive
if [[ -z "$WALLET_NODES_TOTAL" ]] &>/dev/null; then
  WALLET_NODES_TOTAL="${GR:?}0${N0:?}"
fi
if [[ -z "$WALLET_NODES_STABLE" ]] &>/dev/null; then
  WALLET_NODES_STABLE="${GR:?}0${N0:?}"
fi
if [[ -z "$WALLET_NODES_ENABLED" ]] &>/dev/null; then
  WALLET_NODES_ENABLED="${GR:?}0${N0:?}"
fi
if [[ -z "$WALLET_NODES_INQUEUE" ]] &>/dev/null; then
  WALLET_NODES_INQUEUE="${GR:?}0${N0:?}"
fi
if [[ -z "$IP_ADDRESS" ]] &>/dev/null; then
  IP_ADDRESS="${GR:?}0.0.0.0${N0:?}"
fi
if [[ -z "$WALLET_VERSION" ]] &>/dev/null; then
  WALLET_VERSION="${GR:?}0.0.0${N0:?}"
fi
if [[ -z "$WALLET_CHAIN" ]] &>/dev/null; then
  WALLET_CHAIN="${GR:?}0${N0:?}"
fi
if [[ -z "$WALLET_HEADS" ]] &>/dev/null; then
  WALLET_HEADS="${GR:?}0${N0:?}"
fi
if [[ -z "$WALLET_BLOCK" ]] &>/dev/null; then
  WALLET_BLOCK="${GR:?}0${N0:?}"
fi
if [[ -z "$WALLET_PEERS_TOTAL" ]] &>/dev/null; then
  WALLET_PEERS_TOTAL="${GR:?}0${N0:?}"
fi
if [[ -z "$WALLET_PEERS_LATEST" ]] &>/dev/null; then
  WALLET_PEERS_LATEST="${GR:?}0${N0:?}"
fi
if [[ -z "$WALLET_PEERS_OTHER" ]] &>/dev/null; then
  WALLET_PEERS_OTHER="${GR:?}0${N0:?}"
fi
if [[ "$WALLET_PEERS_TOTAL" -eq "0" ]] &>/dev/null; then
  WALLET_PEERS_TOTAL="${GR:?}0${N0:?}"
fi
if [[ "$WALLET_PEERS_LATEST" -eq "0" ]] &>/dev/null; then
  WALLET_PEERS_LATEST="${GR:?}0${N0:?}"
fi
if [[ "$WALLET_PEERS_OTHER" -eq "0" ]] &>/dev/null; then
  WALLET_PEERS_OTHER="${GR:?}0${N0:?}"
fi
if [[ -z "$WALLET_BALANCE" ]] &>/dev/null; then
  WALLET_BALANCE="${GR:?}0.00${N0:?}"
fi
if [[ "$WALLET_BALANCE" -eq "0" ]] &>/dev/null; then
  WALLET_BALANCE="${GR:?}0.00${N0:?}"
fi
if [[ "$WALLET_VALUE" -eq "0" ]] &>/dev/null; then
  WALLET_VALUE="${GR:?}0.00${N0:?}"
fi
if [[ -z "$WALLET_VALUE" ]] &>/dev/null; then
  WALLET_VALUE="${GR:?}0.00${N0:?}"
fi
if [[ -z "$WALLET_MEMPOOL" ]] &>/dev/null; then
  WALLET_MEMPOOL="${GR:?}0${N0:?}"
fi
if [[ -z "$WALLET_TXCOUNT" ]] &>/dev/null; then
  WALLET_TXCOUNT="${GR:?}0${N0:?}"
fi
if [[ -z "$RC_LOADING" ]] &>/dev/null; then
  RC_LOADING=""
fi
if [[ -z "$WALLET_INPUTS" ]] &>/dev/null; then
  WALLET_INPUTS="${GR:?}0${N0:?}"
fi
if [[ "$WALLET_INPUTS" -eq "0" ]] &>/dev/null; then
  WALLET_INPUTS="${GR:?}0${N0:?}"
fi
if [[ -z "$WALLET_STAKES" ]] &>/dev/null; then
  WALLET_STAKES="${GR:?}0${N0:?}"
fi
if [[ -z "$LAST_TX" ]] &>/dev/null; then
  LAST_TX="0"
fi
if [[ -z "$WALLET_TXLAST" ]] &>/dev/null; then
  WALLET_TXLAST="${N0:?}"
fi
if [[ -z "$TIMELINE" ]] &>/dev/null; then
  TIMELINE="${N0:?}"
fi
if [[ -z "$POS_STATUS" ]] &>/dev/null; then
  POS_STATUS="${GR:?}S${GR:?}"
fi
if [[ "$POS_STATUS" -eq "0" ]] &>/dev/null; then
  POS_STATUS="${GR:?}S${GR:?}"
fi

# END
