#!/bin/bash

# By Rainman
# V20221502
# 0.3.5.9

# shellcheck disable=SC2034  # Unused variables left for readability

########## config ##############################################################

source /usr/local/bin/include/pinode.conf

########## sync_progress_bar ###################################################

# save progress
grep -o "progress=........" "${WALLET_LOG_DIR:?}"/debug.log 2>&1 | egrep -o "[0-9]+.[0-9]+" 2>&1 | tail -1 >"${LOG_DIR:?}"/node_data/client/tmp/proc 2>&1

# when debug.log says wallet is synced, this stops here
if wc -l "${LOG_DIR:?}"/node_data/synced 2>&1 | awk '{ print $1 }' &>/dev/null; then
  # look for 'progress=1' line, save it there and then
  grep "progress=1" "${WALLET_LOG_DIR:?}"/debug.log 2>&1 | tail -1 >"${LOG_DIR:?}"/node_data/synced 2>&1

  # greater than n seconds, continue
  if [[ "$(cat "${LOG_DIR:?}"/node_data/uptime 2>/dev/null)" -gt "1" ]] &>/dev/null; then
    # make sure proc exist
    touch "${LOG_DIR:?}"/node_data/client/tmp/proc &>/dev/null

    # output progress value several times
    SYNCING_REPLACE_TX=$(egrep "[0-9]+" "${LOG_DIR:?}"/node_data/client/tmp/proc 2>&1 | tr -d '.' 2>&1 | sed 's/^0*//' 2>&1)

    if [[ -z "$SYNCING_REPLACE_TX" ]] &>/dev/null; then
      # non responsive
      SYNCING_REPLACE_TX="0"
    fi

    # 1000     = 0.100000 %
    # 10000    = 1.000000 %
    # 24852    = 2.485200 %
    # 558213   = 55.82130 %
    # 1000000  = 100.0000 %

    # syncing blockchain with progress bar
    SYNC_PROGRESS_BAR=$(
      if [ "$SYNCING_REPLACE_TX" -gt "990000" ] &>/dev/null; then
        echo -ne "     ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓ 100%\\r"
      else
        # is less than 99
        if [ -z "$SYNCING_REPLACE_TX" ] &>/dev/null; then
          echo -ne "     Loading············································ %\\r"
        fi
        # is less than 99
        if [ "$SYNCING_REPLACE_TX" -lt "10000" ] &>/dev/null; then
          echo -ne "     ··················································· 0%\\r"
        fi
        # is equal to
        if [ "$SYNCING_REPLACE_TX" -ge "10000" ] &>/dev/null; then
          echo -ne "     ▓·················································· 1%\\r"
        fi
        if [ "$SYNCING_REPLACE_TX" -ge "20000" ] &>/dev/null; then
          echo -ne "     ▓▓················································· 2%\\r"
        fi
        if [ "$SYNCING_REPLACE_TX" -ge "30000" ] &>/dev/null; then
          echo -ne "     ▓▓▓················································ 3%\\r"
        fi
        if [ "$SYNCING_REPLACE_TX" -ge "40000" ] &>/dev/null; then
          echo -ne "     ▓▓▓▓··············································· 4%\\r"
        fi
        if [ "$SYNCING_REPLACE_TX" -ge "50000" ] &>/dev/null; then
          echo -ne "     ▓▓▓▓▓·············································· 5%\\r"
        fi
        if [ "$SYNCING_REPLACE_TX" -ge "60000" ] &>/dev/null; then
          echo -ne "     ▓▓▓▓▓▓············································· 6%\\r"
        fi
        if [ "$SYNCING_REPLACE_TX" -ge "70000" ] &>/dev/null; then
          echo -ne "     ▓▓▓▓▓▓▓············································ 7%\\r"
        fi
        if [ "$SYNCING_REPLACE_TX" -ge "80000" ] &>/dev/null; then
          echo -ne "     ▓▓▓▓▓▓▓▓··········································· 8%\\r"
        fi
        if [ "$SYNCING_REPLACE_TX" -ge "90000" ] &>/dev/null; then
          echo -ne "     ▓▓▓▓▓▓▓▓▓·········································· 9%\\r"
        fi
        if [ "$SYNCING_REPLACE_TX" -ge "100000" ] &>/dev/null; then
          echo -ne "     ▓▓▓▓▓▓▓▓▓▓········································· 10%\\r"
        fi
        if [ "$SYNCING_REPLACE_TX" -ge "110000" ] &>/dev/null; then
          echo -ne "     ▓▓▓▓▓▓▓▓▓▓········································· 11%\\r"
        fi
        if [ "$SYNCING_REPLACE_TX" -ge "120000" ] &>/dev/null; then
          echo -ne "     ▓▓▓▓▓▓▓▓▓▓▓········································ 12%\\r"
        fi
        if [ "$SYNCING_REPLACE_TX" -ge "130000" ] &>/dev/null; then
          echo -ne "     ▓▓▓▓▓▓▓▓▓▓▓········································ 13%\\r"
        fi
        if [ "$SYNCING_REPLACE_TX" -ge "140000" ] &>/dev/null; then
          echo -ne "     ▓▓▓▓▓▓▓▓▓▓▓········································ 14%\\r"
        fi
        if [ "$SYNCING_REPLACE_TX" -ge "150000" ] &>/dev/null; then
          echo -ne "     ▓▓▓▓▓▓▓▓▓▓▓▓······································· 15%\\r"
        fi
        if [ "$SYNCING_REPLACE_TX" -ge "160000" ] &>/dev/null; then
          echo -ne "     ▓▓▓▓▓▓▓▓▓▓▓▓······································· 16%\\r"
        fi
        if [ "$SYNCING_REPLACE_TX" -ge "170000" ] &>/dev/null; then
          echo -ne "     ▓▓▓▓▓▓▓▓▓▓▓▓▓······································ 17%\\r"
        fi
        if [ "$SYNCING_REPLACE_TX" -ge "180000" ] &>/dev/null; then
          echo -ne "     ▓▓▓▓▓▓▓▓▓▓▓▓▓······································ 18%\\r"
        fi
        if [ "$SYNCING_REPLACE_TX" -ge "190000" ] &>/dev/null; then
          echo -ne "     ▓▓▓▓▓▓▓▓▓▓▓▓▓······································ 19%\\r"
        fi
        if [ "$SYNCING_REPLACE_TX" -ge "200000" ] &>/dev/null; then
          echo -ne "     ▓▓▓▓▓▓▓▓▓▓▓▓▓▓····································· 20%\\r"
        fi
        if [ "$SYNCING_REPLACE_TX" -ge "210000" ] &>/dev/null; then
          echo -ne "     ▓▓▓▓▓▓▓▓▓▓▓▓▓▓····································· 21%\\r"
        fi
        if [ "$SYNCING_REPLACE_TX" -ge "220000" ] &>/dev/null; then
          echo -ne "     ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓···································· 22%\\r"
        fi
        if [ "$SYNCING_REPLACE_TX" -ge "230000" ] &>/dev/null; then
          echo -ne "     ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓···································· 23%\\r"
        fi
        if [ "$SYNCING_REPLACE_TX" -ge "240000" ] &>/dev/null; then
          echo -ne "     ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓···································· 24%\\r"
        fi
        if [ "$SYNCING_REPLACE_TX" -ge "250000" ] &>/dev/null; then
          echo -ne "     ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓··································· 25%\\r"
        fi
        if [ "$SYNCING_REPLACE_TX" -ge "260000" ] &>/dev/null; then
          echo -ne "     ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓··································· 26%\\r"
        fi
        if [ "$SYNCING_REPLACE_TX" -ge "270000" ] &>/dev/null; then
          echo -ne "     ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓·································· 27%\\r"
        fi
        if [ "$SYNCING_REPLACE_TX" -ge "280000" ] &>/dev/null; then
          echo -ne "     ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓·································· 28%\\r"
        fi
        if [ "$SYNCING_REPLACE_TX" -ge "290000" ] &>/dev/null; then
          echo -ne "     ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓·································· 29%\\r"
        fi
        if [ "$SYNCING_REPLACE_TX" -ge "300000" ] &>/dev/null; then
          echo -ne "     ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓································· 30%\\r"
        fi
        if [ "$SYNCING_REPLACE_TX" -ge "310000" ] &>/dev/null; then
          echo -ne "     ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓································· 31%\\r"
        fi
        if [ "$SYNCING_REPLACE_TX" -ge "320000" ] &>/dev/null; then
          echo -ne "     ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓································ 32%\\r"
        fi
        if [ "$SYNCING_REPLACE_TX" -ge "330000" ] &>/dev/null; then
          echo -ne "     ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓································ 33%\\r"
        fi
        if [ "$SYNCING_REPLACE_TX" -ge "340000" ] &>/dev/null; then
          echo -ne "     ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓································ 34%\\r"
        fi
        if [ "$SYNCING_REPLACE_TX" -ge "350000" ] &>/dev/null; then
          echo -ne "     ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓······························· 35%\\r"
        fi
        if [ "$SYNCING_REPLACE_TX" -ge "360000" ] &>/dev/null; then
          echo -ne "     ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓······························· 36%\\r"
        fi
        if [ "$SYNCING_REPLACE_TX" -ge "370000" ] &>/dev/null; then
          echo -ne "     ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓······························ 37%\\r"
        fi
        if [ "$SYNCING_REPLACE_TX" -ge "380000" ] &>/dev/null; then
          echo -ne "     ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓······························ 38%\\r"
        fi
        if [ "$SYNCING_REPLACE_TX" -ge "390000" ] &>/dev/null; then
          echo -ne "     ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓······························ 39%\\r"
        fi
        if [ "$SYNCING_REPLACE_TX" -ge "400000" ] &>/dev/null; then
          echo -ne "     ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓····························· 40%\\r"
        fi
        if [ "$SYNCING_REPLACE_TX" -ge "410000" ] &>/dev/null; then
          echo -ne "     ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓····························· 41%\\r"
        fi
        if [ "$SYNCING_REPLACE_TX" -ge "420000" ] &>/dev/null; then
          echo -ne "     ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓···························· 42%\\r"
        fi
        if [ "$SYNCING_REPLACE_TX" -ge "430000" ] &>/dev/null; then
          echo -ne "     ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓···························· 43%\\r"
        fi
        if [ "$SYNCING_REPLACE_TX" -ge "440000" ] &>/dev/null; then
          echo -ne "     ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓···························· 44%\\r"
        fi
        if [ "$SYNCING_REPLACE_TX" -ge "450000" ] &>/dev/null; then
          echo -ne "     ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓··························· 45%\\r"
        fi
        if [ "$SYNCING_REPLACE_TX" -ge "460000" ] &>/dev/null; then
          echo -ne "     ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓··························· 46%\\r"
        fi
        if [ "$SYNCING_REPLACE_TX" -ge "470000" ] &>/dev/null; then
          echo -ne "     ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓·························· 47%\\r"
        fi
        if [ "$SYNCING_REPLACE_TX" -ge "480000" ] &>/dev/null; then
          echo -ne "     ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓·························· 48%\\r"
        fi
        if [ "$SYNCING_REPLACE_TX" -ge "490000" ] &>/dev/null; then
          echo -ne "     ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓·························· 49%\\r"
        fi
        if [ "$SYNCING_REPLACE_TX" -ge "500000" ] &>/dev/null; then
          echo -ne "     ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓························· 50%\\r"
        fi
        if [ "$SYNCING_REPLACE_TX" -ge "510000" ] &>/dev/null; then
          echo -ne "     ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓························· 51%\\r"
        fi
        if [ "$SYNCING_REPLACE_TX" -ge "520000" ] &>/dev/null; then
          echo -ne "     ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓························ 52%\\r"
        fi
        if [ "$SYNCING_REPLACE_TX" -ge "530000" ] &>/dev/null; then
          echo -ne "     ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓························ 53%\\r"
        fi
        if [ "$SYNCING_REPLACE_TX" -ge "540000" ] &>/dev/null; then
          echo -ne "     ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓························ 54%\\r"
        fi
        if [ "$SYNCING_REPLACE_TX" -ge "550000" ] &>/dev/null; then
          echo -ne "     ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓······················· 55%\\r"
        fi
        if [ "$SYNCING_REPLACE_TX" -ge "560000" ] &>/dev/null; then
          echo -ne "     ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓······················· 56%\\r"
        fi
        if [ "$SYNCING_REPLACE_TX" -ge "570000" ] &>/dev/null; then
          echo -ne "     ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓······················ 57%\\r"
        fi
        if [ "$SYNCING_REPLACE_TX" -ge "580000" ] &>/dev/null; then
          echo -ne "     ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓······················ 58%\\r"
        fi
        if [ "$SYNCING_REPLACE_TX" -ge "590000" ] &>/dev/null; then
          echo -ne "     ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓······················ 59%\\r"
        fi
        if [ "$SYNCING_REPLACE_TX" -ge "600000" ] &>/dev/null; then
          echo -ne "     ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓····················· 60%\\r"
        fi
        if [ "$SYNCING_REPLACE_TX" -ge "610000" ] &>/dev/null; then
          echo -ne "     ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓····················· 61%\\r"
        fi
        if [ "$SYNCING_REPLACE_TX" -ge "620000" ] &>/dev/null; then
          echo -ne "     ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓···················· 62%\\r"
        fi
        if [ "$SYNCING_REPLACE_TX" -ge "630000" ] &>/dev/null; then
          echo -ne "     ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓···················· 63%\\r"
        fi
        if [ "$SYNCING_REPLACE_TX" -ge "640000" ] &>/dev/null; then
          echo -ne "     ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓···················· 64%\\r"
        fi
        if [ "$SYNCING_REPLACE_TX" -ge "650000" ] &>/dev/null; then
          echo -ne "     ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓··················· 65%\\r"
        fi
        if [ "$SYNCING_REPLACE_TX" -ge "660000" ] &>/dev/null; then
          echo -ne "     ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓··················· 66%\\r"
        fi
        if [ "$SYNCING_REPLACE_TX" -ge "670000" ] &>/dev/null; then
          echo -ne "     ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓·················· 67%\\r"
        fi
        if [ "$SYNCING_REPLACE_TX" -ge "680000" ] &>/dev/null; then
          echo -ne "     ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓·················· 68%\\r"
        fi
        if [ "$SYNCING_REPLACE_TX" -ge "690000" ] &>/dev/null; then
          echo -ne "     ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓·················· 69%\\r"
        fi
        if [ "$SYNCING_REPLACE_TX" -ge "700000" ] &>/dev/null; then
          echo -ne "     ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓················· 70%\\r"
        fi
        if [ "$SYNCING_REPLACE_TX" -ge "710000" ] &>/dev/null; then
          echo -ne "     ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓················· 71%\\r"
        fi
        if [ "$SYNCING_REPLACE_TX" -ge "720000" ] &>/dev/null; then
          echo -ne "     ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓················ 72%\\r"
        fi
        if [ "$SYNCING_REPLACE_TX" -ge "730000" ] &>/dev/null; then
          echo -ne "     ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓················ 73%\\r"
        fi
        if [ "$SYNCING_REPLACE_TX" -ge "740000" ] &>/dev/null; then
          echo -ne "     ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓················ 74%\\r"
        fi
        if [ "$SYNCING_REPLACE_TX" -ge "750000" ] &>/dev/null; then
          echo -ne "     ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓··············· 75%\\r"
        fi
        if [ "$SYNCING_REPLACE_TX" -ge "760000" ] &>/dev/null; then
          echo -ne "     ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓··············· 76%\\r"
        fi
        if [ "$SYNCING_REPLACE_TX" -ge "770000" ] &>/dev/null; then
          echo -ne "     ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓·············· 77%\\r"
        fi
        if [ "$SYNCING_REPLACE_TX" -ge "780000" ] &>/dev/null; then
          echo -ne "     ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓·············· 78%\\r"
        fi
        if [ "$SYNCING_REPLACE_TX" -ge "790000" ] &>/dev/null; then
          echo -ne "     ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓·············· 79%\\r"
        fi
        if [ "$SYNCING_REPLACE_TX" -ge "800000" ] &>/dev/null; then
          echo -ne "     ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓············· 80%\\r"
        fi
        if [ "$SYNCING_REPLACE_TX" -ge "810000" ] &>/dev/null; then
          echo -ne "     ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓············· 81%\\r"
        fi
        if [ "$SYNCING_REPLACE_TX" -ge "820000" ] &>/dev/null; then
          echo -ne "     ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓············ 82%\\r"
        fi
        if [ "$SYNCING_REPLACE_TX" -ge "830000" ] &>/dev/null; then
          echo -ne "     ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓············ 83%\\r"
        fi
        if [ "$SYNCING_REPLACE_TX" -ge "840000" ] &>/dev/null; then
          echo -ne "     ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓············ 84%\\r"
        fi
        if [ "$SYNCING_REPLACE_TX" -ge "850000" ] &>/dev/null; then
          echo -ne "     ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓··········· 85%\\r"
        fi
        if [ "$SYNCING_REPLACE_TX" -ge "860000" ] &>/dev/null; then
          echo -ne "     ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓··········· 86%\\r"
        fi
        if [ "$SYNCING_REPLACE_TX" -ge "870000" ] &>/dev/null; then
          echo -ne "     ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓·········· 87%\\r"
        fi
        if [ "$SYNCING_REPLACE_TX" -ge "880000" ] &>/dev/null; then
          echo -ne "     ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓·········· 88%\\r"
        fi
        if [ "$SYNCING_REPLACE_TX" -ge "890000" ] &>/dev/null; then
          echo -ne "     ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓·········· 89%\\r"
        fi
        if [ "$SYNCING_REPLACE_TX" -ge "900000" ] &>/dev/null; then
          echo -ne "     ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓········· 90%\\r"
        fi
        if [ "$SYNCING_REPLACE_TX" -ge "910000" ] &>/dev/null; then
          echo -ne "     ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓········ 91%\\r"
        fi
        if [ "$SYNCING_REPLACE_TX" -ge "920000" ] &>/dev/null; then
          echo -ne "     ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓······· 92%\\r"
        fi
        if [ "$SYNCING_REPLACE_TX" -ge "930000" ] &>/dev/null; then
          echo -ne "     ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓······ 93%\\r"
        fi
        if [ "$SYNCING_REPLACE_TX" -ge "940000" ] &>/dev/null; then
          echo -ne "     ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓····· 94%\\r"
        fi
        if [ "$SYNCING_REPLACE_TX" -ge "950000" ] &>/dev/null; then
          echo -ne "     ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓···· 95%\\r"
        fi
        if [ "$SYNCING_REPLACE_TX" -ge "960000" ] &>/dev/null; then
          echo -ne "     ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓··· 96%\\r"
        fi
        if [ "$SYNCING_REPLACE_TX" -ge "970000" ] &>/dev/null; then
          echo -ne "     ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓·· 97%\\r"
        fi
        if [ "$SYNCING_REPLACE_TX" -ge "980000" ] &>/dev/null; then
          echo -ne "     ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓· 98%\\r"
        fi
        if [ "$SYNCING_REPLACE_TX" -ge "990000" ] &>/dev/null; then
          echo -ne "     ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓ 99%\\r"
        fi
        WALLET_TXLAST="$SYNCING_REPLACE_TX"
      fi
    ) ### sync should be done ##################################################
  fi
fi

# END
