#!/bin/bash

################################################################################

source /etc/pi-node/include/color
source /etc/pi-node/config

################################################################################
# daemon
################################################################################

# if no PID
if [[ "$(pidof freedomcoind | wc -l)" -eq "0" ]] &>/dev/null; then
  printf '%b' "[${G1}OK${N0}] Daemon  : "
  # start daemon default
  /usr/local/bin/./freedomcoind -debug=tor -proxy="${PROXY:?}" -daemon
fi

# END
