#!/bin/bash

################################################################################

for (( ; ; )); do # loop dashbord

  source /etc/pi-node/include/color
  source /etc/pi-node/config

  ##############################################################################
  # start node daemon
  ##############################################################################

  # daemon running
  if [[ "$(pidof freedomcoind | wc -l)" -eq "0" ]] &>/dev/null; then
    printf '%b' "[${G1}OK${N0}] Daemon  : "
    # start daemon
    /usr/local/bin/./freedomcoind -debug=tor -proxy="${PROXY:?}" -daemon
  fi
  sleep 60
done

# END
