#!/bin/bash

# By Rainman
# V20212912
# 0.4.5.0

source /home/pi/pitrump.conf
source /usr/local/bin/include/color

# date for logs
LOG_DATE=$(date '+%Y-%m-%dT%TZ' 2>&1)

# node_stats directory
mkdir /home/"$(whoami)"/stats &>/dev/null

### install needed packages ####################################################

# rrdtool setup (graphs, round robin database)
if ! [ -x "$(command -v rrdtool)" ]; then
  sudo mkdir /var/lib/rrd &>/dev/null
  sudo mkdir /var/www/html/rrdtool &>/dev/null
  sudo chown -R "$(whoami)":"$(whoami)" /var/lib/rrd
  sudo apt-get install librrds-perl rrdtool -y 2>&1
fi

# apache2 setup (webserver, php)
if ! [ -x "$(command -v apache2)" ]; then
  sudo apt-get install apache2 php libapache2-mod-php -y 2>&1
  sudo chown -R "$(whoami)":"$(whoami)" /var/www/html
  rm /var/www/html/index.html &>/dev/null
  printf '%b' "[${G1:?}OK${N0:?}] Restarting Apache\n"
  sudo systemctl restart apache2 2>&1
  LOCAL=$(ifconfig 2>&1 | grep "inet" 2>&1 | head -1 2>&1 |
    sed -En 's/127.0.0.1//;s/.*inet (addr:)?(([0-9]*\.){3}[0-9]*).*/\2/p' 2>&1)
  echo "[!!] Try your $LOCAL IP Address"
  echo
  read -r -p "Press Enter to continue" </dev/tty
  echo
fi

### create round robin databases for system (rrdtool) ##########################

# load 1
if [ ! -f "/home/$(whoami)/stats/load.rrd" ]; then
  printf '%b' "${LOG_DATE:?} Status() rrdtoolStats() Creating load.rrd! ${CY:?}<>${N0:?}\n" >>"${WALLET_LOG_DIR:?}"/debug.log 2>&1
  rrdtool create /home/"$(whoami)"/stats/load.rrd \
    --step=60 \
    DS:load:GAUGE:300:U:U \
    RRA:AVERAGE:0.5:1:86400 \
    RRA:AVERAGE:0.5:1440:400
fi
# load 5
if [ ! -f "/home/$(whoami)/stats/load5.rrd" ]; then
  printf '%b' "${LOG_DATE:?} Status() rrdtoolStats() Creating load5.rrd! ${CY:?}<>${N0:?}\n" >>"${WALLET_LOG_DIR:?}"/debug.log 2>&1
  rrdtool create /home/"$(whoami)"/stats/load5.rrd \
    --step=60 \
    DS:load5:GAUGE:300:U:U \
    RRA:AVERAGE:0.5:1:86400 \
    RRA:AVERAGE:0.5:1440:400
fi
# load 15
if [ ! -f "/home/$(whoami)/stats/load15.rrd" ]; then
  printf '%b' "${LOG_DATE:?} Status() rrdtoolStats() Creating load15.rrd! ${CY:?}<>${N0:?}\n" >>"${WALLET_LOG_DIR:?}"/debug.log 2>&1
  rrdtool create /home/"$(whoami)"/stats/load15.rrd \
    --step=60 \
    DS:load15:GAUGE:300:U:U \
    RRA:AVERAGE:0.5:1:86400 \
    RRA:AVERAGE:0.5:1440:400
fi
# temp
if [ ! -f "/home/$(whoami)/stats/temp.rrd" ]; then
  printf '%b' "${LOG_DATE:?} Status() rrdtoolStats() Creating temp.rrd! ${CY:?}<>${N0:?}\n" >>"${WALLET_LOG_DIR:?}"/debug.log 2>&1
  rrdtool create /home/"$(whoami)"/stats/temp.rrd \
    --step=60 \
    DS:temp:GAUGE:300:U:U \
    RRA:AVERAGE:0.5:1:86400 \
    RRA:AVERAGE:0.5:1440:400
fi
# memory available
if [ ! -f "/home/$(whoami)/stats/memory_total.rrd" ]; then
  printf '%b' "${LOG_DATE:?} Status() rrdtoolStats() Creating memory_total.rrd! ${CY:?}<>${N0:?}\n" >>"${WALLET_LOG_DIR:?}"/debug.log 2>&1
  rrdtool create /home/"$(whoami)"/stats/memory_total.rrd \
    --step=60 \
    DS:memory_total:GAUGE:300:U:U \
    RRA:AVERAGE:0.5:1:86400 \
    RRA:AVERAGE:0.5:1440:400
fi
# memory free
if [ ! -f "/home/$(whoami)/stats/memory_free.rrd" ]; then
  printf '%b' "${LOG_DATE:?} Status() rrdtoolStats() Creating memory_free.rrd! ${CY:?}<>${N0:?}\n" >>"${WALLET_LOG_DIR:?}"/debug.log 2>&1
  rrdtool create /home/"$(whoami)"/stats/memory_free.rrd \
    --step=60 \
    DS:memory_free:GAUGE:300:U:U \
    RRA:AVERAGE:0.5:1:86400 \
    RRA:AVERAGE:0.5:1440:400
fi
# hdd
if [ ! -f "/home/$(whoami)/stats/hdd.rrd" ]; then
  printf '%b' "${LOG_DATE:?} Status() rrdtoolStats() Creating hdd.rrd! ${CY:?}<>${N0:?}\n" >>"${WALLET_LOG_DIR:?}"/debug.log 2>&1
  rrdtool create /home/"$(whoami)"/stats/hdd.rrd \
    --step=60 \
    DS:hdd:GAUGE:300:U:U \
    RRA:AVERAGE:0.5:1:86400 \
    RRA:AVERAGE:0.5:1440:400
fi
# download
if [ ! -f "/home/$(whoami)/stats/net_down.rrd" ]; then
  printf '%b' "${LOG_DATE:?} Status() rrdtoolStats() Creating net_down.rrd! ${CY:?}<>${N0:?}\n" >>"${WALLET_LOG_DIR:?}"/debug.log 2>&1
  rrdtool create /home/"$(whoami)"/stats/net_down.rrd \
    --step=60 \
    DS:net_down:GAUGE:300:U:U \
    RRA:AVERAGE:0.5:1:86400 \
    RRA:AVERAGE:0.5:1440:400
fi
# upload
if [ ! -f "/home/$(whoami)/stats/net_up.rrd" ]; then
  printf '%b' "${LOG_DATE:?} Status() rrdtoolStats() Creating net_up.rrd! ${CY:?}<>${N0:?}\n" >>"${WALLET_LOG_DIR:?}"/debug.log 2>&1
  rrdtool create /home/"$(whoami)"/stats/net_up.rrd \
    --step=60 \
    DS:net_up:GAUGE:300:U:U \
    RRA:AVERAGE:0.5:1:86400 \
    RRA:AVERAGE:0.5:1440:400
fi

### create round robin databases for wallet (rrdtool) ##########################

# balance
if [ ! -f "/home/$(whoami)/stats/balance.rrd" ]; then
  printf '%b' "${LOG_DATE:?} Status() rrdtoolStats() Creating balance.rrd! ${CY:?}<>${N0:?}\n" >>"${WALLET_LOG_DIR:?}"/debug.log 2>&1
  rrdtool create /home/"$(whoami)"/stats/balance.rrd \
    --step=60 \
    DS:balance:GAUGE:300:U:U \
    RRA:AVERAGE:0.5:1:86400 \
    RRA:AVERAGE:0.5:1440:400
fi
# stakes
if [ ! -f "/home/$(whoami)/stats/stakes.rrd" ]; then
  printf '%b' "${LOG_DATE:?} Status() rrdtoolStats() Creating stakes.rrd! ${CY:?}<>${N0:?}\n" >>"${WALLET_LOG_DIR:?}"/debug.log 2>&1
  rrdtool create /home/"$(whoami)"/stats/stakes.rrd \
    --step=60 \
    DS:stakes:GAUGE:300:U:U \
    RRA:AVERAGE:0.5:1:86400 \
    RRA:AVERAGE:0.5:1440:400
fi
# inputs
if [ ! -f "/home/$(whoami)/stats/inputs.rrd" ]; then
  printf '%b' "${LOG_DATE:?} Status() rrdtoolStats() Creating inputs.rrd! ${CY:?}<>${N0:?}\n" >>"${WALLET_LOG_DIR:?}"/debug.log 2>&1
  rrdtool create /home/"$(whoami)"/stats/inputs.rrd \
    --step=60 \
    DS:inputs:GAUGE:300:U:U \
    RRA:AVERAGE:0.5:1:86400 \
    RRA:AVERAGE:0.5:1440:400
fi
# peers
if [ ! -f "/home/$(whoami)/stats/peers.rrd" ]; then
  printf '%b' "${LOG_DATE:?} Status() rrdtoolStats() Creating peers.rrd! ${CY:?}<>${N0:?}\n" >>"${WALLET_LOG_DIR:?}"/debug.log 2>&1
  rrdtool create /home/"$(whoami)"/stats/peers.rrd \
    --step=60 \
    DS:peers:GAUGE:300:U:U \
    RRA:AVERAGE:0.5:1:86400 \
    RRA:AVERAGE:0.5:1440:400
fi
# mempool
if [ ! -f "/home/$(whoami)/stats/mempool.rrd" ]; then
  printf '%b' "${LOG_DATE:?} Status() rrdtoolStats() Creating mempool.rrd! ${CY:?}<>${N0:?}\n" >>"${WALLET_LOG_DIR:?}"/debug.log 2>&1
  rrdtool create /home/"$(whoami)"/stats/mempool.rrd \
    --step=60 \
    DS:mempool:GAUGE:300:U:U \
    RRA:AVERAGE:0.5:1:86400 \
    RRA:AVERAGE:0.5:1440:400
fi

### update rrdtool databases ###################################################

# wallet daemon uptime function
# function for waiting with stuff before a limit (seconds) is reached
function uptime_daemon() {
  PID="$(pidof trumpcoind 2>&1)"
  HZ=$(getconf CLK_TCK 2>&1)
  UPTIME_CMD=$(awk '{print $1}' </proc/uptime)
  STARTTIME=$(awk '{print $22}' </proc/"$PID"/stat)
  echo $(("${UPTIME_CMD%.*}" - "$STARTTIME" / "$HZ"))
}

# greater than n seconds, continue
if [[ "$(uptime_daemon)" -gt "600" ]] &>/dev/null; then

  rrdtool update /home/"$(whoami)"/stats/load.rrd N:"$(cat "${LOG_DIR:?}"/node_data/load 2>/dev/null | tr -d ',' 2>&1 | awk '{ print $1 }' 2>&1)"
  rrdtool update /home/"$(whoami)"/stats/load5.rrd N:"$(cat "${LOG_DIR:?}"/node_data/load 2>/dev/null | tr -d ',' 2>&1 | awk '{ print $2 }' 2>&1)"
  rrdtool update /home/"$(whoami)"/stats/load15.rrd N:"$(cat "${LOG_DIR:?}"/node_data/load 2>/dev/null | tr -d ',' 2>&1 | awk '{ print $3 }' 2>&1)"
  rrdtool update /home/"$(whoami)"/stats/temp.rrd N:"$(echo "$(</sys/class/thermal/thermal_zone0/temp) / 100 * 0.1" | bc)"
  rrdtool update /home/"$(whoami)"/stats/memory_total.rrd N:"$(cat "${LOG_DIR:?}"/node_data/stats.total_mem 2>/dev/null)"
  rrdtool update /home/"$(whoami)"/stats/memory_free.rrd N:"$(cat "${LOG_DIR:?}"/node_data/stats.free_mem 2>/dev/null)"
  rrdtool update /home/"$(whoami)"/stats/hdd.rrd N:"$(echo "$(df 2>&1 | egrep "mmcblk0p2|mmcblk0p3|/dev/root" 2>&1 | awk '{ print $3 }' 2>&1)*1024" 2>&1 | bc -l 2>&1)"
  rrdtool update /home/"$(whoami)"/stats/net_down.rrd N:"$(egrep -o "[0-9]+.[0-9]+" "${LOG_DIR:?}"/node_data/stats.download 2>&1)"
  rrdtool update /home/"$(whoami)"/stats/net_up.rrd N:"$(egrep -o "[0-9]+.[0-9]+" "${LOG_DIR:?}"/node_data/stats.upload 2>&1)"
  rrdtool update /home/"$(whoami)"/stats/balance.rrd N:"$(grep "balance" /tmp/node_data/getinfo 2>&1 | egrep -o "[0-9]+.[0-9]+" 2>&1 | awk '{ printf "%.2f\n", $1 }' 2>&1)"
  rrdtool update /home/"$(whoami)"/stats/stakes.rrd N:"$(grep -c "BitcoinMiner" "${WALLET_DIR:?}"/staking 2>&1)"
  rrdtool update /home/"$(whoami)"/stats/inputs.rrd N:"$(grep "address" /tmp/node_data/listunspent 2>&1 | wc -l 2>&1)"
  rrdtool update /home/"$(whoami)"/stats/mempool.rrd N:"$(grep "size" /tmp/node_data/getmempoolinfo 2>&1 | egrep -o "[0-9]+" 2>&1)"
  rrdtool update /home/"$(whoami)"/stats/peers.rrd N:"$(grep "connections" "${LOG_DIR:?}"/node_data/getinfo 2>&1 | awk '{ print $2 }' 2>&1)"

fi

#### create index.php ##########################################################

cat >/var/www/html/index.php <<'EOF'
<div id="content" align="center">
<?php
  header("refresh: 60;");
?>
<?php
  // background color (dark blue)
  echo "<body style='background-color:2D3037'>";
  // graphs
  echo "<img src='load_graph.png' alt='Load' />";
  echo "<img src='temp_graph.png' alt='CPUTemp' />";
  echo "<img src='memory_graph.png' alt='Memory' />";
  echo "<img src='hdd_graph.png' alt='Drive' />";
  echo "<img src='network_graph.png' alt='Network' />";
  echo "<img src='balance_graph.png' alt='Balance' />";
  echo "<img src='stakes_graph.png' alt='Stakes' />";
  echo "<img src='inputs_graph.png' alt='Inputs' />";
  echo "<img src='peers_graph.png' alt='Peers' />";
  echo "<img src='mempool_graph.png' alt='Mempool' />";
EOF

#### create shell (graphs) #####################################################

cat <<<'#!/bin/bash

# loadavg 1,5,15m (24hour)
rrdtool graph /var/www/html/load_graph.png \
-w 400 -h 164 -a PNG \
--slope-mode \
--start -24hour --end now \
--vertical-label "System Load" \
--color BACK#565875 \
--color FONT#FFFFFF \
--color CANVAS#42445F \
--color GRID#565875 \
--color FRAME#565875 \
--color SHADEA#565875 \
--color SHADEB#565875 \
DEF:load=/home/"$(whoami)"/stats/load.rrd:load:MAX \
DEF:load5=/home/"$(whoami)"/stats/load5.rrd:load5:MAX \
DEF:load15=/home/"$(whoami)"/stats/load15.rrd:load15:MAX \
GPRINT:load:LAST:%.2lf\ 1M \
GPRINT:load5:AVERAGE:%.2lf\ 5M \
GPRINT:load15:AVERAGE:%.2lf\ 15M \
LINE1:load#00FF33:"Load 1m" \
LINE1:load5#FFE000:"Load 5m" \
LINE1:load15#FF5100:"Load 15m"

# inputs (24hour)
rrdtool graph /var/www/html/inputs_graph.png \
-w 400 -h 164 -a PNG \
--slope-mode \
--start -24hour --end now \
--vertical-label "Wallet Inputs" \
--alt-autoscale-max --lower-limit=1 \
--color BACK#565875 \
--color FONT#FFFFFF \
--color CANVAS#42445F \
--color GRID#565875 \
--color FRAME#565875 \
--color SHADEA#565875 \
--color SHADEB#565875 \
DEF:inputs=/home/"$(whoami)"/stats/inputs.rrd:inputs:MAX \
GPRINT:inputs:LAST:%.0lf\ Now \
GPRINT:inputs:MAX:%.0lf\ Max \
GPRINT:inputs:MIN:%.0lf\ Min \
AREA:inputs#6CE564:"Inputs"

# peers (24hour)
rrdtool graph /var/www/html/peers_graph.png \
-w 400 -h 164 -a PNG \
--slope-mode \
--start -24hour --end now \
--vertical-label "Peers (P2P)" \
--alt-autoscale-max --lower-limit=1 \
--color BACK#565875 \
--color FONT#FFFFFF \
--color CANVAS#42445F \
--color GRID#565875 \
--color FRAME#565875 \
--color SHADEA#565875 \
--color SHADEB#565875 \
DEF:peers=/home/"$(whoami)"/stats/peers.rrd:peers:MAX \
GPRINT:peers:LAST:%.0lf\ Now \
GPRINT:peers:AVERAGE:%.0lf\ AVG \
GPRINT:peers:MAX:%.0lf\ Max \
GPRINT:peers:MIN:%.0lf\ Min \
AREA:peers#9633FF:"Peers"

# stakes (24hour)
rrdtool graph /var/www/html/stakes_graph.png \
-w 400 -h 164 -a PNG \
--slope-mode \
--start -24hour --end now \
--vertical-label "Wallet Stakes" \
--alt-autoscale-max --lower-limit=1 \
--color BACK#565875 \
--color FONT#FFFFFF \
--color CANVAS#42445F \
--color GRID#565875 \
--color FRAME#565875 \
--color SHADEA#565875 \
--color SHADEB#565875 \
DEF:stakes=/home/"$(whoami)"/stats/stakes.rrd:stakes:MAX \
GPRINT:stakes:LAST:%.0lf\ Now \
GPRINT:stakes:AVERAGE:%.0lf\ AVG \
GPRINT:stakes:MAX:%.0lf\ Max \
GPRINT:stakes:MIN:%.0lf\ Min \
AREA:stakes#FFB777:"Stakes"

# balance (24hour)
rrdtool graph /var/www/html/balance_graph.png \
-w 400 -h 164 -a PNG \
--slope-mode \
--start -24hour --end now \
--vertical-label "Wallet Balance" \
--alt-autoscale-max --lower-limit=1 \
--color BACK#565875 \
--color FONT#FFFFFF \
--color CANVAS#42445F \
--color GRID#565875 \
--color FRAME#565875 \
--color SHADEA#565875 \
--color SHADEB#565875 \
DEF:balance=/home/"$(whoami)"/stats/balance.rrd:balance:MAX \
GPRINT:balance:LAST:%.2lf\ Trump \
GPRINT:balance:MAX:%.2lf\ Max \
GPRINT:balance:MIN:%.2lf\ Min \
AREA:balance#3F79E5:"Balance"

# network (24hour)
rrdtool graph /var/www/html/network_graph.png \
-w 400 -h 164 -a PNG \
--slope-mode \
--start -24hour --end now \
--vertical-label "Network" \
--color BACK#565875 \
--color FONT#FFFFFF \
--color CANVAS#42445F \
--color GRID#565875 \
--color FRAME#565875 \
--color SHADEA#565875 \
--color SHADEB#565875 \
DEF:net_down=/home/"$(whoami)"/stats/net_down.rrd:net_down:MAX \
DEF:net_up=/home/"$(whoami)"/stats/net_up.rrd:net_up:MAX \
GPRINT:net_down:LAST:%.0lf\ Bytes\ Down \
GPRINT:net_up:LAST:%.0lf\ Bytes\ Up \
LINE1:net_down#00FF00:"Down" \
LINE2:net_up#FF3A00:"Up"

# hdd (24hour)
rrdtool graph /var/www/html/hdd_graph.png \
-w 400 -h 164 -a PNG \
--slope-mode \
--start -24hour --end now \
--vertical-label "System Drive" \
--alt-autoscale-max --lower-limit=1 \
--color BACK#565875 \
--color FONT#FFFFFF \
--color CANVAS#42445F \
--color GRID#565875 \
--color FRAME#565875 \
--color SHADEA#565875 \
--color SHADEB#565875 \
DEF:hdd=/home/"$(whoami)"/stats/hdd.rrd:hdd:MAX \
GPRINT:hdd:MAX:%.0lf\ Bytes\ Max \
GPRINT:hdd:MIN:%.0lf\ Bytes\ Min \
AREA:hdd#F17EFF:"UsedHDD"

# memory (24hour)
rrdtool graph /var/www/html/memory_graph.png \
-w 400 -h 164 -a PNG \
--slope-mode \
--start -24hour --end now \
--vertical-label "Memory (MB)" \
--color BACK#565875 \
--color FONT#FFFFFF \
--color CANVAS#42445F \
--color GRID#565875 \
--color FRAME#565875 \
--color SHADEA#565875 \
--color SHADEB#565875 \
DEF:memory_total=/home/"$(whoami)"/stats/memory_total.rrd:memory_total:MAX \
DEF:memory_free=/home/"$(whoami)"/stats/memory_free.rrd:memory_free:MAX \
GPRINT:memory_total:MAX:%.2lf\M\ Total \
GPRINT:memory_free:LAST:%.2lf\M\ Free \
AREA:memory_total#3BBCE5:"Total" \
AREA:memory_free#5BE545:"Free"

# cpu temperature (24hour)
rrdtool graph /var/www/html/temp_graph.png \
-w 400 -h 164 -a PNG \
--slope-mode \
--start -24hour --end now \
--vertical-label "CPU Temp (°C)" \
--color BACK#565875 \
--color FONT#FFFFFF \
--color CANVAS#42445F \
--color GRID#565875 \
--color FRAME#565875 \
--color SHADEA#565875 \
--color SHADEB#565875 \
DEF:temp=/home/"$(whoami)"/stats/temp.rrd:temp:MAX \
GPRINT:temp:LAST:%.2lf\°C\ Now \
GPRINT:temp:AVERAGE:%.2lf\°C\ AVG \
GPRINT:temp:MAX:%.2lf\°C\ Max \
GPRINT:temp:MIN:%.2lf\°C\ Min \
AREA:temp#FF2D00:"CPUTemp"

# mempool (24hour)
rrdtool graph /var/www/html/mempool_graph.png \
-w 1394 -h 164 -a PNG \
--slope-mode \
--start -24hour --end now \
--vertical-label "Wallet Mempool" \
--alt-autoscale-max --lower-limit=1 \
--color BACK#565875 \
--color FONT#FFFFFF \
--color CANVAS#42445F \
--color GRID#565875 \
--color FRAME#565875 \
--color SHADEA#565875 \
--color SHADEB#565875 \
DEF:mempool=/home/"$(whoami)"/stats/mempool.rrd:mempool:MAX \
GPRINT:mempool:LAST:%.0lf\ Now \
GPRINT:mempool:AVERAGE:%.0lf\ AVG \
GPRINT:mempool:MAX:%.0lf\ Max \
GPRINT:mempool:MIN:%.0lf\ Min \
AREA:mempool#FF0000:"Mempool"' >/tmp/graphs

# greater than n seconds, continue
if [[ "$(uptime_daemon)" -gt "600" ]] &>/dev/null; then

  # note: heavy reading, do interval reading with date:time
  if [[ "$(date '+%T' 2>&1 | egrep "[0-9]+:[0-9]+5:[0-9]+|[0-9]+:[0-9]+0:[0-9]+" 2>&1)" ]] &>/dev/null; then
    # run graphs script
    printf '%b' "${LOG_DATE:?} Status() rrdtoolStats() Creating graphs.${N0:?}\n" >>"${WALLET_LOG_DIR:?}"/debug.log 2>&1
    bash /tmp/graphs &>/dev/null && clear
  else
    printf '%b' "${LOG_DATE:?} Status() rrdtoolStats() Saving data.${N0:?}\n" >>"${WALLET_LOG_DIR:?}"/debug.log 2>&1
  fi
fi

# END
