#!/bin/bash

# By Rainman
# V20222001
# 0.2.9.6

source /home/pi/pitrump.conf
source /usr/local/bin/include/color

# date for logs
LOG_DATE=$(cat "${LOG_DIR:?}"/node_data/stats/date 2>/dev/null)

if [ ! -d /home/"$(whoami)"/stats ] &>/dev/null; then
  # node_stats directory
  mkdir /home/"$(whoami)"/stats &>/dev/null
fi

### install needed packages ####################################################

# rrdtool setup (graphs, round robin database)
if ! [ -x "$(command -v rrdtool)" ] &>/dev/null; then
  sudo mkdir /var/lib/rrd &>/dev/null
  sudo chown -R "$(whoami)":"$(whoami)" /var/lib/rrd
  sudo apt-get install librrds-perl rrdtool -y 2>&1
fi

# apache2 setup (webserver, php)
if ! [ -x "$(command -v apache2)" ] &>/dev/null; then
  sudo apt-get install apache2 php libapache2-mod-php -y 2>&1
  sudo chown -R "$(whoami)":"$(whoami)" /var/www/html
  rm /var/www/html/index.html &>/dev/null
  printf '%b' "[${G1:?}OK${N0:?}] Restarting Apache\n"
  sudo systemctl restart apache2 2>&1
  LOCAL=$(ifconfig 2>&1 | grep "inet" 2>&1 | head -1 2>&1 |
    sed -En 's/127.0.0.1//;s/.*inet (addr:)?(([0-9]*\.){3}[0-9]*).*/\2/p' 2>&1)
  echo "[!!] Try your $LOCAL IP Address"
  echo
  read -r -p "[Ok] Press Enter to continue" </dev/tty
  echo
fi

### create round robin databases for system (rrdtool) ##########################

# load 1
if [ ! -f "/home/$(whoami)/stats/load.rrd" ] &>/dev/null; then
  printf '%b' "${LOG_DATE:?} Status() rrdtoolStats() Creating load.rrd! ${CY:?}<>${N0:?}\n" >>"${WALLET_LOG_DIR:?}"/debug.log 2>&1
  rrdtool create /home/"$(whoami)"/stats/load.rrd \
    --step=60 \
    DS:load:GAUGE:300:U:U \
    RRA:AVERAGE:0.5:1:315360
fi
# load 5
if [ ! -f "/home/$(whoami)/stats/load5.rrd" ] &>/dev/null; then
  printf '%b' "${LOG_DATE:?} Status() rrdtoolStats() Creating load5.rrd! ${CY:?}<>${N0:?}\n" >>"${WALLET_LOG_DIR:?}"/debug.log 2>&1
  rrdtool create /home/"$(whoami)"/stats/load5.rrd \
    --step=60 \
    DS:load5:GAUGE:300:U:U \
    RRA:AVERAGE:0.5:1:315360
fi
# load 15
if [ ! -f "/home/$(whoami)/stats/load15.rrd" ] &>/dev/null; then
  printf '%b' "${LOG_DATE:?} Status() rrdtoolStats() Creating load15.rrd! ${CY:?}<>${N0:?}\n" >>"${WALLET_LOG_DIR:?}"/debug.log 2>&1
  rrdtool create /home/"$(whoami)"/stats/load15.rrd \
    --step=60 \
    DS:load15:GAUGE:300:U:U \
    RRA:AVERAGE:0.5:1:315360
fi
# temp
if [ ! -f "/home/$(whoami)/stats/temp.rrd" ] &>/dev/null; then
  printf '%b' "${LOG_DATE:?} Status() rrdtoolStats() Creating temp.rrd! ${CY:?}<>${N0:?}\n" >>"${WALLET_LOG_DIR:?}"/debug.log 2>&1
  rrdtool create /home/"$(whoami)"/stats/temp.rrd \
    --step=60 \
    DS:temp:GAUGE:300:U:U \
    RRA:AVERAGE:0.5:1:315360
fi
# memory available
if [ ! -f "/home/$(whoami)/stats/memory_total.rrd" ] &>/dev/null; then
  printf '%b' "${LOG_DATE:?} Status() rrdtoolStats() Creating memory_total.rrd! ${CY:?}<>${N0:?}\n" >>"${WALLET_LOG_DIR:?}"/debug.log 2>&1
  rrdtool create /home/"$(whoami)"/stats/memory_total.rrd \
    --step=60 \
    DS:memory_total:GAUGE:300:U:U \
    RRA:AVERAGE:0.5:1:315360
fi
# memory free
if [ ! -f "/home/$(whoami)/stats/memory_free.rrd" ] &>/dev/null; then
  printf '%b' "${LOG_DATE:?} Status() rrdtoolStats() Creating memory_free.rrd! ${CY:?}<>${N0:?}\n" >>"${WALLET_LOG_DIR:?}"/debug.log 2>&1
  rrdtool create /home/"$(whoami)"/stats/memory_free.rrd \
    --step=60 \
    DS:memory_free:GAUGE:300:U:U \
    RRA:AVERAGE:0.5:1:315360
fi
# hdd
if [ ! -f "/home/$(whoami)/stats/hdd.rrd" ] &>/dev/null; then
  printf '%b' "${LOG_DATE:?} Status() rrdtoolStats() Creating hdd.rrd! ${CY:?}<>${N0:?}\n" >>"${WALLET_LOG_DIR:?}"/debug.log 2>&1
  rrdtool create /home/"$(whoami)"/stats/hdd.rrd \
    --step=60 \
    DS:hdd:GAUGE:300:U:U \
    RRA:AVERAGE:0.5:1:315360
fi
# hdd total
if [ ! -f "/home/$(whoami)/stats/hdd_total.rrd" ] &>/dev/null; then
  printf '%b' "${LOG_DATE:?} Status() rrdtoolStats() Creating hdd_total.rrd! ${CY:?}<>${N0:?}\n" >>"${WALLET_LOG_DIR:?}"/debug.log 2>&1
  rrdtool create /home/"$(whoami)"/stats/hdd_total.rrd \
    --step=60 \
    DS:hdd_total:GAUGE:300:U:U \
    RRA:AVERAGE:0.5:1:315360
fi
# network
if [ ! -f "/home/$(whoami)/stats/network.rrd" ] &>/dev/null; then
  printf '%b' "${LOG_DATE:?} Status() rrdtoolStats() Creating network.rrd! ${CY:?}<>${N0:?}\n" >>"${WALLET_LOG_DIR:?}"/debug.log 2>&1
  rrdtool create /home/"$(whoami)"/stats/network.rrd \
    --step=60 \
    DS:rxbytes:DERIVE:300:U:U \
    DS:txbytes:DERIVE:300:U:U \
    RRA:AVERAGE:0.5:1:315360
fi

### create round robin databases for wallet (rrdtool) ##########################

# balance
if [ ! -f "/home/$(whoami)/stats/balance.rrd" ] &>/dev/null; then
  printf '%b' "${LOG_DATE:?} Status() rrdtoolStats() Creating balance.rrd! ${CY:?}<>${N0:?}\n" >>"${WALLET_LOG_DIR:?}"/debug.log 2>&1
  rrdtool create /home/"$(whoami)"/stats/balance.rrd \
    --step=60 \
    DS:balance:GAUGE:300:U:U \
    RRA:AVERAGE:0.5:1:315360
fi
# balance value
if [ ! -f "/home/$(whoami)/stats/value.rrd" ] &>/dev/null; then
  printf '%b' "${LOG_DATE:?} Status() rrdtoolStats() Creating value.rrd! ${CY:?}<>${N0:?}\n" >>"${WALLET_LOG_DIR:?}"/debug.log 2>&1
  rrdtool create /home/"$(whoami)"/stats/value.rrd \
    --step=60 \
    DS:value:GAUGE:300:U:U \
    RRA:AVERAGE:0.5:1:315360
fi
# stakes
if [ ! -f "/home/$(whoami)/stats/stakes.rrd" ] &>/dev/null; then
  printf '%b' "${LOG_DATE:?} Status() rrdtoolStats() Creating stakes.rrd! ${CY:?}<>${N0:?}\n" >>"${WALLET_LOG_DIR:?}"/debug.log 2>&1
  rrdtool create /home/"$(whoami)"/stats/stakes.rrd \
    --step=60 \
    DS:stakes:GAUGE:300:U:U \
    RRA:AVERAGE:0.5:1:315360
fi
# inputs
if [ ! -f "/home/$(whoami)/stats/inputs.rrd" ] &>/dev/null; then
  printf '%b' "${LOG_DATE:?} Status() rrdtoolStats() Creating inputs.rrd! ${CY:?}<>${N0:?}\n" >>"${WALLET_LOG_DIR:?}"/debug.log 2>&1
  rrdtool create /home/"$(whoami)"/stats/inputs.rrd \
    --step=60 \
    DS:inputs:GAUGE:300:U:U \
    RRA:AVERAGE:0.5:1:315360
fi
# peers
if [ ! -f "/home/$(whoami)/stats/peers.rrd" ] &>/dev/null; then
  printf '%b' "${LOG_DATE:?} Status() rrdtoolStats() Creating peers.rrd! ${CY:?}<>${N0:?}\n" >>"${WALLET_LOG_DIR:?}"/debug.log 2>&1
  rrdtool create /home/"$(whoami)"/stats/peers.rrd \
    --step=60 \
    DS:peers:GAUGE:300:U:U \
    RRA:AVERAGE:0.5:1:315360
fi
# difficulty
if [ ! -f "/home/$(whoami)/stats/difficulty.rrd" ] &>/dev/null; then
  printf '%b' "${LOG_DATE:?} Status() rrdtoolStats() Creating difficulty.rrd! ${CY:?}<>${N0:?}\n" >>"${WALLET_LOG_DIR:?}"/debug.log 2>&1
  rrdtool create /home/"$(whoami)"/stats/difficulty.rrd \
    --step=60 \
    DS:difficulty:GAUGE:300:U:U \
    RRA:AVERAGE:0.5:1:315360
fi
# set auto pos (difficulty)
if [ ! -f "/home/$(whoami)/stats/set_auto_pos.rrd" ] &>/dev/null; then
  printf '%b' "${LOG_DATE:?} Status() rrdtoolStats() Creating set_auto_pos.rrd! ${CY:?}<>${N0:?}\n" >>"${WALLET_LOG_DIR:?}"/debug.log 2>&1
  rrdtool create /home/"$(whoami)"/stats/set_auto_pos.rrd \
    --step=60 \
    DS:set_auto_pos:GAUGE:300:U:U \
    RRA:AVERAGE:0.5:1:315360
fi
# set auto con (confirmation)
if [ ! -f "/home/$(whoami)/stats/set_auto_con.rrd" ] &>/dev/null; then
  printf '%b' "${LOG_DATE:?} Status() rrdtoolStats() Creating set_auto_con.rrd! ${CY:?}<>${N0:?}\n" >>"${WALLET_LOG_DIR:?}"/debug.log 2>&1
  rrdtool create /home/"$(whoami)"/stats/set_auto_con.rrd \
    --step=60 \
    DS:set_auto_con:GAUGE:300:U:U \
    RRA:AVERAGE:0.5:1:315360
fi
# total confirmations
if [ ! -f "/home/$(whoami)/stats/total_tx.rrd" ] &>/dev/null; then
  printf '%b' "${LOG_DATE:?} Status() rrdtoolStats() Creating total_tx.rrd! ${CY:?}<>${N0:?}\n" >>"${WALLET_LOG_DIR:?}"/debug.log 2>&1
  rrdtool create /home/"$(whoami)"/stats/total_tx.rrd \
    --step=60 \
    DS:total_tx:GAUGE:300:U:U \
    RRA:AVERAGE:0.5:1:315360
fi
# total confirmations q
if [ ! -f "/home/$(whoami)/stats/total_tx_q.rrd" ] &>/dev/null; then
  printf '%b' "${LOG_DATE:?} Status() rrdtoolStats() Creating total_tx_q.rrd! ${CY:?}<>${N0:?}\n" >>"${WALLET_LOG_DIR:?}"/debug.log 2>&1
  rrdtool create /home/"$(whoami)"/stats/total_tx_q.rrd \
    --step=60 \
    DS:total_tx_q:GAUGE:300:U:U \
    RRA:AVERAGE:0.5:1:315360
fi

### update rrdtool databases ###################################################

# greater than n seconds, continue
if [[ "$(cat "${LOG_DIR:?}"/node_data/uptime 2>/dev/null)" -gt "300" ]] &>/dev/null; then

  rrdtool update /home/"$(whoami)"/stats/load.rrd N:"$(cat "${LOG_DIR:?}"/node_data/stats/load 2>/dev/null | tr -d ',' 2>&1 | awk '{ print $1 }' 2>&1)"
  rrdtool update /home/"$(whoami)"/stats/load5.rrd N:"$(cat "${LOG_DIR:?}"/node_data/stats/load 2>/dev/null | tr -d ',' 2>&1 | awk '{ print $2 }' 2>&1)"
  rrdtool update /home/"$(whoami)"/stats/load15.rrd N:"$(cat "${LOG_DIR:?}"/node_data/stats/load 2>/dev/null | tr -d ',' 2>&1 | awk '{ print $3 }' 2>&1)"
  rrdtool update /home/"$(whoami)"/stats/temp.rrd N:"$(echo "$(</sys/class/thermal/thermal_zone0/temp) / 100 * 0.1" | bc)"
  rrdtool update /home/"$(whoami)"/stats/memory_total.rrd N:"$(cat "${LOG_DIR:?}"/node_data/stats/memtotal 2>/dev/null)"
  rrdtool update /home/"$(whoami)"/stats/memory_free.rrd N:"$(cat "${LOG_DIR:?}"/node_data/stats/memfree 2>/dev/null)"
  rrdtool update /home/"$(whoami)"/stats/hdd.rrd N:"$(echo "$(df 2>&1 | egrep "mmcblk0p2|mmcblk0p3|/dev/root" 2>&1 | awk '{ print $3 }' 2>&1)/1024/1024" 2>&1 | bc -l 2>&1)"
  rrdtool update /home/"$(whoami)"/stats/hdd_total.rrd N:"$(echo "$(df 2>&1 | egrep "mmcblk0p2|mmcblk0p3|/dev/root" 2>&1 | awk '{ print $2 }' 2>&1)/1024/1024" 2>&1 | bc -l 2>&1)"
  rrdtool update /home/"$(whoami)"/stats/network.rrd N:"$(cat "${LOG_DIR:?}"/node_data/stats/rxbytes 2>/dev/null)":"$(cat "${LOG_DIR:?}"/node_data/stats/txbytes 2>/dev/null)"
  rrdtool update /home/"$(whoami)"/stats/balance.rrd N:"$(cat "$LOG_DIR"/node_data/stats/total_balance 2>/dev/null)"
  rrdtool update /home/"$(whoami)"/stats/value.rrd N:"$(cat "$LOG_DIR"/node_data/stats/balance_value 2>/dev/null)"
  rrdtool update /home/"$(whoami)"/stats/stakes.rrd N:"$(grep -c "BitcoinMiner" "${WALLET_DIR:?}"/staking 2>&1)"
  rrdtool update /home/"$(whoami)"/stats/inputs.rrd N:"$(grep "address" "${LOG_DIR:?}"/node_data/client/listunspent 2>&1 | wc -l 2>&1)"
  rrdtool update /home/"$(whoami)"/stats/peers.rrd N:"$(grep "connections" "${LOG_DIR:?}"/node_data/client/getinfo 2>&1 | awk '{ print $2 }' 2>&1)"
  rrdtool update /home/"$(whoami)"/stats/difficulty.rrd N:"$(grep "difficulty" "${LOG_DIR:?}"/node_data/client/getinfo 2>&1 | awk '{ print $2 }' 2>&1)"

  # auto pos config
  if [[ "$AUTO_POS" -eq "2" ]] &>/dev/null; then

    # get autocombine threshold
    CON_DIFF=$(grep "autocombine_threshold" "${LOG_DIR:?}"/node_data/client/getwalletinfo 2>&1 | awk '{ print $2 }' 2>&1 | awk -F. '{ print $1 }' 2>&1)
    # get total confirmations from inputs that are below the con_diff var (withouth not_post_input var)
    TOTAL_CONF_BELOW=$(egrep "amount.*" "${LOG_DIR:?}"/node_data/client/listunspent 2>&1 | awk -F: '{if($2<'"${CON_DIFF:?}"')print$2}' 2>&1 | awk '{ SUM += $1} END { print SUM }' 2>&1 | awk -F. '{ print $1 }' 2>&1)

    if [[ "$(echo "$(cat "$LOG_DIR"/node_data/stats/total_balance 2>/dev/null)/$(cat "$LOG_DIR"/node_data/stats/difficulty_avg 2>/dev/null)" 2>&1 | bc -l 2>&1 | awk -F. '{ print $1 }' 2>&1)" -gt "1" ]] &>/dev/null; then
      POS_LIMIT="${POS_LIMIT:?}"
    else
      POS_LIMIT=$(cat "${LOG_DIR:?}"/node_data/stats/lim_pos 2>/dev/null)
    fi

    # get amount of inputs with lower value than var con_diff
    grep "amount" "${LOG_DIR:?}"/node_data/client/listunspent 2>&1 | awk '{ print $2 }' 2>&1 | awk -F. '{ print $1 }' 2>&1 | sort -n 2>&1 | awk '$1 < '"${CON_DIFF:?}"' { print }' 2>&1 | wc -l >"${LOG_DIR:?}"/node_data/stats/not_pos 2>&1
    NOT_POS_INPUT=$(cat "${LOG_DIR:?}"/node_data/stats/not_pos 2>/dev/null)

    # get amount of inputs, disregard with var not_pos_input value
    rrdtool update /home/"$(whoami)"/stats/total_tx.rrd N:"$(echo "$(echo "$(grep "confirmations" "${LOG_DIR:?}"/node_data/client/listunspent 2>&1 | awk '{ print $2 }' 2>&1 | awk '{ SUM += $1} END { print SUM }' 2>&1)-${TOTAL_CONF_BELOW:?}" 2>&1 | bc 2>&1)/$(echo "$(grep "address" "${LOG_DIR:?}"/node_data/client/listunspent 2>&1 | wc -l 2>&1)+${NOT_POS_INPUT:?}" 2>&1 | bc 2>&1)" 2>&1 | bc 2>&1)"
    rrdtool update /home/"$(whoami)"/stats/total_tx_q.rrd N:"$(echo "$(echo "$(grep "confirmations" "${LOG_DIR:?}"/node_data/client/listunspent 2>&1 | awk '{ print $2 }' 2>&1 | awk '{ SUM += $1} END { print SUM }' 2>&1)-${TOTAL_CONF_BELOW:?}" 2>&1 | bc 2>&1)/$(echo "$(grep "address" "${LOG_DIR:?}"/node_data/client/listunspent 2>&1 | wc -l 2>&1)" 2>&1 | bc 2>&1)" 2>&1 | bc 2>&1)"
  else
    if [[ "$AUTO_POS" -eq "1" ]] &>/dev/null; then

      # get total confirmations from inputs that are below the con_diff var (withouth not_post_input var)
      TOTAL_CONF_BELOW=$(egrep "amount.*" "${LOG_DIR:?}"/node_data/client/listunspent 2>&1 | awk -F: '{if($2<'"${CON_DIFF:?}"')print$2}' 2>&1 | awk '{ SUM += $1} END { print SUM }' 2>&1 | awk -F. '{ print $1 }' 2>&1)

      rrdtool update /home/"$(whoami)"/stats/total_tx.rrd N:"$(echo "$(echo "$(grep "confirmations" "${LOG_DIR:?}"/node_data/client/listunspent 2>&1 | awk '{ print $2 }' 2>&1 | awk '{ SUM += $1} END { print SUM }' 2>&1)-${TOTAL_CONF_BELOW:?}" 2>&1 | bc 2>&1)/$(echo "$(grep "address" "${LOG_DIR:?}"/node_data/client/listunspent 2>&1 | wc -l 2>&1)" 2>&1 | bc 2>&1)" 2>&1 | bc 2>&1)"
    else
      # original normal values
      rrdtool update /home/"$(whoami)"/stats/total_tx.rrd N:"$(echo "$(grep "confirmations" "${LOG_DIR:?}"/node_data/client/listunspent 2>&1 | awk '{ print $2 }' 2>&1 | awk '{ SUM += $1} END { print SUM }' 2>&1)/$(grep "address" "${LOG_DIR:?}"/node_data/client/listunspent 2>&1 | wc -l 2>&1)" 2>&1 | bc 2>&1)"
    fi
  fi
  rrdtool update /home/"$(whoami)"/stats/set_auto_pos.rrd N:"$(grep "threshold" "${LOG_DIR:?}"/node_data/client/getwalletinfo 2>&1 | awk '{ print $2 }' 2>&1 | awk -F. '{ print $1 }' 2>&1)"
  rrdtool update /home/"$(whoami)"/stats/set_auto_con.rrd N:"${POS_LIMIT:?}"
fi

#### create index.php ##########################################################

cat >/var/www/html/index.php <<'EOF'
<div id="content" align="center">
<?php
  header("refresh: 120;");
?>
<?php
  // background color (dark blue)
  echo "<body style='background-color:2D3037'>";
  // graphs
  echo "<img src='load_graph.png' alt='Load' />";
  echo "<img src='temp_graph.png' alt='CPUTemp' />";
  echo "<img src='memory_graph.png' alt='Memory' />";
  echo "<img src='hdd_graph.png' alt='Drive' />";
  echo "<img src='network_graph.png' alt='Network' />";
  echo "<img src='balance_graph.png' alt='Balance' />";
  echo "<img src='stakes_graph.png' alt='Stakes' />";
  echo "<img src='inputs_graph.png' alt='Inputs' />";
  echo "<img src='peers_graph.png' alt='Peers' />";
  echo "<img src='total_tx_graph.png' alt='Total TX' />";
  echo "<img src='difficulty_graph.png' alt='Difficulty' />";
EOF

# greater than n seconds, continue
if [[ "$(cat "${LOG_DIR:?}"/node_data/uptime 2>/dev/null)" -gt "1" ]] &>/dev/null; then

  # note: heavy reading, do interval reading with date:time
  if [[ "$(date '+%T' 2>&1 | egrep "[0-9]+:[0-9]+0:[0-9]+" 2>&1)" ]] &>/dev/null; then
    # run graphs script
    printf '%b' "${LOG_DATE:?} Status() rrdtoolStats() Creating graphs.${N0:?}\n" >>"${WALLET_LOG_DIR:?}"/debug.log 2>&1
    bash /usr/local/bin/include/graphs &>/dev/null && clear
  else
    printf '%b' "${LOG_DATE:?} Status() rrdtoolStats() Saving data.${N0:?}\n" >>"${WALLET_LOG_DIR:?}"/debug.log 2>&1
  fi
fi

# END
