#!/bin/bash

# By Rainman
# V20221211
# 0.0.2.1

# system user
WHOAMI=$(whoami)

if [[ ! -f /usr/local/bin/include/pinode/pinode.conf ]] &>/dev/null; then
  cp /home/"${WHOAMI:?}"/pi-node/pinode.conf /tmp/pinode.conf.tmp &>/dev/null
  sudo mv /tmp/pinode.conf.tmp /usr/local/bin/include/pinode/pinode.conf &>/dev/null
fi
source /usr/local/bin/include/pinode/pinode.conf 2>&1

touch /tmp/updating &>/dev/null
clear
# update repo
cd /home/"${WHOAMI:?}"/pi-node || exit && git pull -q 2>/dev/null && bash /home/"${WHOAMI:?}"/pi-node/include/install 2>/dev/null

# END
