#!/bin/bash

source /etc/pi-node/include/color

################################################################################

clear
# update pi-node files
printf '%b' "[${N0}!!${N0}] Github  : Updating pi-node repository..\n"
printf '%b' "[${G1}OK${N0}] Github  : $(cd || exit && cd pi-node && git pull)\n"
printf '%b' "[${N0}!!${N0}] Install : Updating include..\n"
cd || exit && cp -rf pi-node/include /etc/pi-node
printf '%b' "[${N0}!!${N0}] Script  : Updating ${G1}dash${N0}\n"
cd || exit && sudo cp pi-node/dash /usr/local/bin
printf '%b' "[${N0}!!${N0}] Script  : Updating ${G1}update-pi-node${N0}\n"
cd || exit && sudo cp pi-node/include/update /usr/local/bin/update-pi-node.update
sudo chmod +x /usr/local/bin/update-pi-node.update
sudo chown "$(whoami)":"$(whoami)" /usr/local/bin/update-pi-node.update
printf '%b' "[${G1}OK${N0}] Console : Done!\n"
echo "$(date | xargs) - Updated" >/tmp/pnud.tmp
mv /usr/local/bin/update-pi-node.update /usr/local/bin/update-pi-node

# END
