#!/bin/bash

# By Rainman
# V20222002
# 0.0.2.2

if [[ ! -f /tmp/installing ]] &>/dev/null; then
  touch /tmp/updating &>/dev/null
  clear
  if [[ -f /usr/local/bin/include/install ]] &>/dev/null; then
    sudo cp include/install /usr/local/bin/include/install
    sudo chown "$(whoami)":"$(whoami)" /usr/local/bin/include/install 2>&1
  else
    echo "installing" >/tmp/installing 2>&1
    torify bash /usr/local/bin/include/install
  fi
else
  # update repo
  cd /home/"$(whoami)"/pi-node 2>/dev/null || exit && git pull -q 2>/dev/null && bash include/install 2>/dev/null
fi

# END
