#!/bin/bash

################################################################################

source /etc/pi-node/include/color
source /etc/pi-node/config

################################################################################
# progress bar
################################################################################

# if not synced
if [[ ! "$(grep -oP 'progress=\K[0-9.]+' "${WALLET_LOG_DIR}"/debug.log | tail -1 | egrep "[0-9]+.[0-9]+")" == "1.000000" ]] &>/dev/null; then
  # function to draw the progress bar
  draw_progress_bar() {
    PROGRESS="$1"
    local PERCENT
    BAR_WIDTH=50
    local FILLED
    local EMPTY

    PERCENT=$(awk "BEGIN {printf \"%.0f\", $PROGRESS * 100}")
    FILLED=$((PERCENT * BAR_WIDTH / 100))
    EMPTY=$((BAR_WIDTH - FILLED))
    # bar
    printf "["
    for ((I = 0; I < FILLED; I++)); do printf "#"; done
    for ((I = 0; I < EMPTY; I++)); do printf "."; done
    printf "] %s%%\n" "$PERCENT"
  }
  # extract the progress value
  PROGRESS="$(grep -oP 'progress=\K[0-9.]+' "${WALLET_LOG_DIR}"/debug.log | tail -1)"
  # draw the progress bar
  WALLET_TXLAST="$(draw_progress_bar "$PROGRESS")"
fi

################################################################################

REPO_VERSION="$(/usr/local/bin/./freedomcoin-cli -version | tail -1 | awk '{ print $NF }')"

################################################################################

SYSTEM_CLOCK="$(date | awk '{ print $4 }')"

################################################################################

# default
CB="${GR}"

################################################################################

WALLET_POS_REWARDS="$(grep "BitcoinMiner : proof-of-stake block was signed" "${WALLET_LOG_DIR:?}"/debug.log 2>&1 | awk '!a[$0]++' 2>&1 | wc -l)"

# if any rewards
if [[ "$WALLET_POS_REWARDS" -gt "0" ]] &>/dev/null; then
  CB="${G1}"
fi

################################################################################

WALLET_MOVEMENT="$(grep -c "AddToWallet" "${WALLET_LOG_DIR:?}"/debug.log)"

# if any movements
if [[ "$WALLET_MOVEMENT" -gt "0" ]] &>/dev/null; then
  CB="${Y1}"
fi

################################################################################

MASTER_STATUS=""

# if zero
if [[ -z "$MASTER_STATUS" ]] &>/dev/null; then
  MASTER_STATUS="${GR}M${N0}"
fi

################################################################################

PROOF_STATUS=""

# if zero
if [[ -z "$PROOF_STATUS" ]] &>/dev/null; then
  PROOF_STATUS="${GR}S${N0}"
fi

################################################################################

THEME_STATUS=""

# if zero
if [[ -z "$THEME_STATUS" ]] &>/dev/null; then
  THEME_STATUS="${GR}D${N0}"
fi

################################################################################

POS_STATUS=""

# if zero
if [[ -z "$POS_STATUS" ]] &>/dev/null; then
  POS_STATUS="${GR}S${N0}"
fi

################################################################################

SYSTEM_LOAD="$(cat /proc/loadavg 2>/dev/null | awk '{ print $1,$2,$3 }')"

################################################################################

CPU_CTEMP="$(cat /sys/devices/virtual/thermal/thermal_zone?/temp 2>/dev/null | awk '{printf " %5.2f °C\n" , $1/1000}' | xargs)"

# END
